# Generated by Django 4.2.7 on 2025-02-02 15:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Client_Id')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('active_flag', models.CharField(default='Y', max_length=10, null=True, verbose_name='Active Flag')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('address1', models.CharField(max_length=200, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('state', models.CharField(max_length=20, verbose_name='State')),
                ('postalcode', models.CharField(max_length=100, verbose_name='Postal Code')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid US phone number (e.g., +1 123-456-7890, (123) 456-7890, or 1234567890).', regex='^\\+?1?\\s?-?\\(?\\d{3}\\)?\\s?-?\\d{3}\\s?-?\\d{4}$')], verbose_name='Phone Number')),
                ('primaryemail', models.EmailField(max_length=100, verbose_name='Email')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Patient_Id')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('active_flag', models.CharField(default='Y', max_length=10, null=True, verbose_name='Active Flag')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('birth_dt', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(max_length=10, null=True, verbose_name='Gender')),
                ('mrn', models.CharField(max_length=80, verbose_name='MRN')),
                ('ssn', models.CharField(max_length=80, verbose_name='SSN')),
                ('street_address', models.CharField(max_length=100, verbose_name='Street Address')),
                ('apt', models.CharField(blank=True, max_length=80, null=True, verbose_name='Apt/Unit/Suite')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('zipcode', models.CharField(max_length=100, verbose_name='Zipcode')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid US phone number (e.g., +1 123-456-7890, (123) 456-7890, or 1234567890).', regex='^\\+?1?\\s?-?\\(?\\d{3}\\)?\\s?-?\\d{3}\\s?-?\\d{4}$')], verbose_name='Phone Number')),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid fax number in the format (123) 456-7890 or 123-456-7890.', regex='^\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}$')], verbose_name='Fax Number')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Address')),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Marital Status')),
                ('smoking_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Smoking Status')),
                ('race', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ethenicity/Race')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('physician_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Physician_Id')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('external', models.BooleanField(default=False, verbose_name='Is External')),
                ('active_flag', models.CharField(default='Y', max_length=10, null=True, verbose_name='Active Flag')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid US phone number (e.g., +1 123-456-7890, (123) 456-7890, or 1234567890).', regex='^\\+?1?\\s?-?\\(?\\d{3}\\)?\\s?-?\\d{3}\\s?-?\\d{4}$')], verbose_name='Phone Number')),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid fax number in the format (123) 456-7890 or 123-456-7890.', regex='^\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}$')], verbose_name='Fax Number')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Address')),
                ('physician_type', models.CharField(blank=True, default='doctor', max_length=40, null=True, verbose_name='Physician Type')),
                ('title', models.CharField(blank=True, max_length=40, null=True, verbose_name='Title')),
                ('env_type', models.CharField(blank=True, default='clinical', max_length=40, null=True, verbose_name='Env Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_id', to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'physician',
                'verbose_name_plural': 'physicians',
            },
        ),
        migrations.CreateModel(
            name='PatientInsuranceInfo',
            fields=[
                ('patientinfo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Patientinfo ID')),
                ('insurance', models.CharField(max_length=80, verbose_name='Insurance')),
                ('group', models.CharField(max_length=80, verbose_name='Group')),
                ('policy', models.CharField(max_length=80, unique='True', verbose_name='Policy')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.patient', verbose_name='Patient ID')),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurance',
            },
        ),
        migrations.CreateModel(
            name='ClientDoctorInfo',
            fields=[
                ('client_docinfo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Client Doctor Info ID')),
                ('active_flag', models.CharField(default='Y', max_length=10, null=True, verbose_name='Active Flag')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.client', verbose_name='Client ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('physician_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.physician', verbose_name='Physician ID')),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctor',
            },
        ),
        migrations.AddConstraint(
            model_name='patientinsuranceinfo',
            constraint=models.UniqueConstraint(fields=('patient_id', 'policy'), name='unique_patient_id_policy'),
        ),
        migrations.AddConstraint(
            model_name='clientdoctorinfo',
            constraint=models.UniqueConstraint(fields=('client_id', 'physician_id'), name='unique_client_id_physician_id'),
        ),
    ]
