# Generated by Django 4.2.7 on 2025-02-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='clientdoctorinfo',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='physician',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime'),
        ),
    ]
