# Generated by Django 4.2.7 on 2025-03-03 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_alter_client_created_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fax_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid fax number in the format (123) 456-7890 or 123-456-7890.', regex='^\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}$')], verbose_name='Fax Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='clientdoctorinfo',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='patientinsuranceinfo',
            name='patientinfo_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Patient Info ID'),
        ),
        migrations.AlterField(
            model_name='physician',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='physician',
            name='physician_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Physician ID'),
        ),
    ]
