# Generated by Django 4.2.7 on 2025-03-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_client_fax_number_alter_client_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='category',
            field=models.CharField(max_length=20, null=True, verbose_name='Category'),
        ),
    ]
