# Generated by Django 4.2.7 on 2025-04-19 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0004_physician_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessionType',
            fields=[
                ('accession_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Accession Type Id')),
                ('accession_type', models.CharField(max_length=20, unique=True, verbose_name='Accession Type')),
                ('reporting_type', models.CharField(blank=True, choices=[('internal', 'Internal'), ('external', 'External')], max_length=20, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date Time')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Accession Type',
                'verbose_name_plural': 'Accession Types',
            },
        ),
    ]
