# Generated by Django 4.2.7 on 2025-05-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_accessiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Middel Initial'),
        ),
    ]
