# Generated by Django 4.2.7 on 2025-07-07 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0006_patient_middle_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodySite',
            fields=[
                ('body_site_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Body Site Id')),
                ('body_site', models.CharField(max_length=80, unique=True, verbose_name='Body Site')),
                ('base_image', models.CharField(blank=True, max_length=80, null=True, verbose_name='Base Image')),
                ('image_render_category', models.CharField(blank=True, choices=[('category1', 'Category 1'), ('category2', 'Category 2')], max_length=20, null=True, verbose_name='Image Render Category')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date Time')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'BodySite',
                'verbose_name_plural': 'BodySites',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='ReportImgPropInfo',
            fields=[
                ('report_img_prop_info_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Report Img Prop Info Id')),
                ('category', models.CharField(max_length=40, verbose_name='Category')),
                ('shape', models.CharField(blank=True, choices=[('*', 'Star'), ('s', 'Square'), ('^', 'Triangle'), ('D', 'Diamond'), ('o', 'Circle')], max_length=10, null=True, verbose_name='Shape')),
                ('color', models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('black', 'Black')], max_length=20, null=True, verbose_name='Color')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date Time')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Report Image Property',
                'verbose_name_plural': 'Report Image Properties',
            },
        ),
        migrations.CreateModel(
            name='AttachmentConfiguration',
            fields=[
                ('attachment_config_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Attachment Configuration Id')),
                ('model_name', models.CharField(max_length=80, unique=True, verbose_name='Model')),
                ('path', models.CharField(max_length=2000, verbose_name='Path')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date Time')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Attachment Configuration',
                'verbose_name_plural': 'Attachment Configuration',
            },
        ),
        migrations.CreateModel(
            name='BodySubSiteMap',
            fields=[
                ('body_subsite_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Body Subsite Id')),
                ('sub_site', models.CharField(max_length=80, verbose_name='SubSite')),
                ('x_axis', models.IntegerField(blank=True, null=True, verbose_name='X Axis')),
                ('y_axis', models.IntegerField(blank=True, null=True, verbose_name='Y Axis')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime')),
                ('body_site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.bodysite', verbose_name='Body Site')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Subsite',
                'verbose_name_plural': 'Subsites',
                'unique_together': {('body_site', 'sub_site')},
            },
        ),
    ]
