# Generated by Django 4.2.7 on 2025-09-26 05:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0023_testworkflowstepactionmap_workflow_step_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0007_bodysite_alter_client_name_reportimgpropinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioProject',
            fields=[
                ('bioproject_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Project Id')),
                ('project_protocol_id', models.CharField(max_length=40, verbose_name='Project/Protocol Id')),
                ('qc_status', models.CharField(max_length=20, verbose_name='QC Status')),
                ('qced_dt', models.DateTimeField(blank=True, null=True, verbose_name='QCed Date Time')),
                ('qc_reason', models.CharField(blank=True, max_length=2000, null=True, verbose_name='QC Reason')),
                ('instructions', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Project Instructions')),
                ('modification_notes', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Modification Notes')),
                ('client_project_protocol_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Client Project/Protocol ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date Time')),
                ('mod_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified Date Time')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mod_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ProjModifiedBy', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('qced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ProjQCedBy', to=settings.AUTH_USER_MODEL, verbose_name='QCed By')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('patient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='masterdata.patient')),
                ('subject_id', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Subject ID')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
            bases=('masterdata.patient',),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Sponsor Id')),
                ('sponsor_name', models.CharField(max_length=40, null=True, verbose_name='Sponsor Name')),
                ('sponsor_number', models.CharField(max_length=40, null=True, verbose_name='Sponsor Number')),
                ('sponsor_description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Sponsor Description')),
                ('sponsor_address_info', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Sponsor Address Info')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date Time')),
                ('mod_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified Date Time')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mod_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SpnModifiedBy', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='ProjectVisitMap',
            fields=[
                ('project_visit_map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Project Visit Map Id')),
                ('visit_id', models.CharField(max_length=20, verbose_name='Visit ID')),
                ('client_visit_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Client Visit ID')),
                ('visit_instruction', models.CharField(blank=True, max_length=200, null=True, verbose_name='Visit Instruction')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date Time')),
                ('mod_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified Date Time')),
                ('bioproject_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.bioproject', verbose_name='Bio Project')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='project_visitmap_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mod_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='project_visitmap_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Visit Details',
                'verbose_name_plural': 'Visit Details',
            },
        ),
        migrations.CreateModel(
            name='ProjectTestMap',
            fields=[
                ('project_test_map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Project Test Map Id')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date Time')),
                ('mod_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified Date Time')),
                ('bioproject_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.bioproject', verbose_name='Bio Project')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='project_testmap_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mod_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='project_testmap_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tests.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='ProjectEmailMap',
            fields=[
                ('project_email_map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Project Email Map Id')),
                ('email_id', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Email Id')),
                ('email_category', models.CharField(blank=True, max_length=40, null=True, verbose_name='Email Category')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date Time')),
                ('mod_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified Date Time')),
                ('bioproject_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.bioproject', verbose_name='Bio Project')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='project_emailmap_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mod_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='project_emailmap_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Email',
            },
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('emailconfig_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Email Config ID')),
                ('email_category', models.CharField(max_length=40, verbose_name='Email Category')),
                ('email_to', models.CharField(help_text='Multiple email IDs separated by semicolons', max_length=500, verbose_name='Email To')),
                ('email_cc', models.CharField(blank=True, help_text='Multiple email IDs separated by semicolons', max_length=500, null=True, verbose_name='Email CC')),
                ('subject', models.CharField(max_length=255, verbose_name='Email Subject')),
                ('body', models.TextField(verbose_name='Email Body')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('mod_dt', models.DateTimeField(auto_now=True, verbose_name='Modified Date Time')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='emailconfigCreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mod_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='emailconfigModifiedBy', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
        ),
        migrations.CreateModel(
            name='BodySiteTestMap',
            fields=[
                ('bodysite_test_map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Bodysite Test Id')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime')),
                ('mod_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('body_site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.bodysite', verbose_name='Body Site')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testbodysite_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mod_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testbodysite_mod_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.test', verbose_name='Test Id')),
            ],
            options={
                'verbose_name': 'Bodysite Test Map',
                'verbose_name_plural': 'Associated Tests',
            },
        ),
        migrations.CreateModel(
            name='BioSite',
            fields=[
                ('biosite_id', models.AutoField(primary_key=True, serialize=False, verbose_name='BioSite ID')),
                ('site_number', models.CharField(max_length=40, verbose_name='Site Number')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('mod_dt', models.DateTimeField(auto_now=True, verbose_name='Modified Date Time')),
                ('address', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Address')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('city', models.CharField(blank=True, max_length=80, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=80, null=True, verbose_name='State')),
                ('postalcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Postal Code')),
                ('country', models.CharField(max_length=80, verbose_name='Investigator Site Country')),
                ('investigator_name', models.CharField(max_length=200, verbose_name='Investigator Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid US phone number (e.g., +1 123-456-7890, (123) 456-7890, or 1234567890).', regex='^\\+?1?\\s?-?\\(?\\d{3}\\)?\\s?-?\\d{3}\\s?-?\\d{4}$')], verbose_name='Phone Number')),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid fax number in the format (123) 456-7890 or 123-456-7890.', regex='^\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}$')], verbose_name='Fax Number')),
                ('bioproject_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='BioProject', to='masterdata.bioproject', verbose_name='BioProject')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='BioSCreated By')),
                ('mod_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='BioSiteModifiedBy', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('sponsor_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Sponsor', to='masterdata.sponsor', verbose_name='Sponsor')),
            ],
            options={
                'verbose_name': 'Investigator Site',
                'verbose_name_plural': 'Investigator Site',
            },
        ),
        migrations.AddField(
            model_name='bioproject',
            name='sponsor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.sponsor', verbose_name='Sponsor'),
        ),
        migrations.CreateModel(
            name='QCPendingBioProject',
            fields=[
            ],
            options={
                'verbose_name': 'QC Pending Project',
                'verbose_name_plural': 'QC Pending Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('masterdata.bioproject',),
        ),
        migrations.AddConstraint(
            model_name='projectvisitmap',
            constraint=models.UniqueConstraint(fields=('bioproject_id', 'visit_id'), name='unique_project_visit', violation_error_message='This visit is already associated with this project'),
        ),
        migrations.AddConstraint(
            model_name='projecttestmap',
            constraint=models.UniqueConstraint(fields=('bioproject_id', 'test_id'), name='unique_project_test_id', violation_error_message='This test is already associated with this project'),
        ),
        migrations.AlterUniqueTogether(
            name='bodysitetestmap',
            unique_together={('body_site', 'test_id')},
        ),
    ]
