# Generated by Django 4.2.7 on 2025-10-01 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_bioproject_subject_sponsor_projectvisitmap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessionPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_prefix', models.CharField(max_length=10, unique=True, verbose_name='Accession Prefix')),
                ('magazine', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Accession Prefix',
                'verbose_name_plural': 'Accession Prefixes',
                'ordering': ['accession_prefix'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFieldsMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is Visible')),
                ('category', models.CharField(blank=True, choices=[('ACCESSION', 'Accession'), ('SAMPLE', 'Sample')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.bioproject', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Demographic',
                'verbose_name_plural': 'Demographics',
                'unique_together': {('project', 'field_name')},
            },
        ),
    ]
