# Generated by Django 4.2.7 on 2025-10-17 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0009_accessionprefix_projectfieldsmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicFields',
            fields=[
                ('demographicfieldsid', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('model_field_name', models.CharField(max_length=100, verbose_name='Model Field Name')),
                ('category', models.CharField(blank=True, choices=[('ACCESSION', 'Accession'), ('SAMPLE', 'Sample')], max_length=20)),
            ],
            options={
                'verbose_name': 'Demographic Field',
                'verbose_name_plural': 'Demographic Fields',
            },
        ),
        migrations.AddField(
            model_name='projectfieldsmap',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectfieldsmap_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='projectfieldsmap',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime'),
        ),
        migrations.AddField(
            model_name='projectfieldsmap',
            name='mod_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectfieldsmap_mod_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='projectfieldsmap',
            name='mod_dt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime'),
        ),
        migrations.AddField(
            model_name='projectfieldsmap',
            name='model_field_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model Field Name'),
        ),
        migrations.CreateModel(
            name='ProjectPhysicianMap',
            fields=[
                ('project_physician_map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Project Physician Map Id')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date Time')),
                ('mod_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified Date Time')),
                ('bioproject_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.bioproject', verbose_name='Bio Project')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='project_physicianmap_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mod_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='project_physicianmap_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('physician_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.physician', verbose_name='Physician')),
            ],
            options={
                'verbose_name': 'Project Physician Map',
                'verbose_name_plural': 'Project Physician Maps',
            },
        ),
        migrations.AddConstraint(
            model_name='projectphysicianmap',
            constraint=models.UniqueConstraint(fields=('bioproject_id', 'physician_id'), name='unique_project_physician', violation_error_message='This physician is already associated with this project'),
        ),
    ]
