# Generated by Django 4.2.7 on 2025-10-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_demographicfields_projectfieldsmap_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='email_category',
            field=models.CharField(max_length=40, unique=True, verbose_name='Email Category'),
        ),
    ]
