# Generated by Django 4.2.7 on 2025-12-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0011_alter_emailconfig_email_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodysitetestmap',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default'),
        ),
    ]
