# Generated by Django 4.2.7 on 2025-12-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0012_bodysitetestmap_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='MRN'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ssn',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='SSN'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zipcode'),
        ),
    ]
