# Generated by Django 4.2.7 on 2025-03-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihcworkflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ihcworkflow',
            options={'verbose_name': 'IHC Sample', 'verbose_name_plural': 'IHC Samples'},
        ),
        migrations.RemoveField(
            model_name='ihcworkflow',
            name='stain_date',
        ),
        migrations.AddField(
            model_name='ihcworkflow',
            name='image_enddt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ImageEnd DateTime'),
        ),
        migrations.AddField(
            model_name='ihcworkflow',
            name='image_qcstatus',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Image QC Status'),
        ),
        migrations.AddField(
            model_name='ihcworkflow',
            name='image_startdt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Image Start DateTime'),
        ),
        migrations.AddField(
            model_name='ihcworkflow',
            name='is_recordvisible',
            field=models.BooleanField(null=True, verbose_name='Is visible'),
        ),
        migrations.AddField(
            model_name='ihcworkflow',
            name='stain_enddt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stain End DateTime'),
        ),
        migrations.AddField(
            model_name='ihcworkflow',
            name='stain_startdt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stain Start DateTime'),
        ),
    ]
