# Generated by Django 4.2.7 on 2025-04-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihcworkflow', '0002_alter_ihcworkflow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihcworkflow',
            name='image_qcdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Image QC DateTime'),
        ),
    ]
