# Generated by Django 4.2.7 on 2025-08-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihcworkflow', '0003_ihcworkflow_image_qcdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihcworkflow',
            name='staining_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Staining Status'),
        ),
        migrations.AddField(
            model_name='ihcworkflow',
            name='staining_technique',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Staining Technique'),
        ),
    ]
