# Generated by Django 4.2.7 on 2025-01-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jobtypes',
            field=models.ManyToManyField(blank=True, help_text='The job types this user belongs to. A user will get all permissions granted to each of their job types.', related_name='users', related_query_name='jobtype', to='security.jobtype', verbose_name='jobtypes'),
        ),
    ]
