# Generated by Django 4.2.7 on 2025-01-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_user_jobtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.AddField(
            model_name='jobtype',
            name='departmentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.department', verbose_name='Department'),
        ),
    ]
