# Generated by Django 4.2.7 on 2025-01-11 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_department_jobtype_departmentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='departmentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.department', verbose_name='Department'),
        ),
    ]
