# Generated by Django 4.2.7 on 2025-01-20 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_site_department_siteid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='siteid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.site', verbose_name='Site'),
        ),
    ]
