# Generated by Django 4.2.7 on 2025-01-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_alter_department_siteid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='site_independent',
            field=models.BooleanField(default=False, verbose_name='Is Site Independent'),
        ),
    ]
