# Generated by Django 4.2.7 on 2025-01-21 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_jobtype_site_independent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'site timezone',
                'verbose_name_plural': 'site timezones',
            },
        ),
        migrations.AddField(
            model_name='site',
            name='timezone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.sitetimezone', verbose_name='Timezone'),
        ),
    ]
