# Generated by Django 4.2.7 on 2025-01-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_sitetimezone_site_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetimezone',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='description'),
        ),
    ]
