# Generated by Django 4.2.7 on 2025-01-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_sitetimezone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='abbreviation',
            field=models.CharField(max_length=20, null=True, verbose_name='Abbreviation'),
        ),
    ]
