# Generated by Django 4.2.7 on 2025-01-28 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
        ('security', '0010_site_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrinterInfo',
            fields=[
                ('user_printer_info_id', models.AutoField(primary_key=True, serialize=False, verbose_name='User Printer Info ID')),
                ('printer_category', models.CharField(verbose_name='Printer Category')),
                ('is_default', models.CharField(blank=True, max_length=10, null=True, verbose_name='Is Default')),
                ('jobtype_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='security.jobtype', verbose_name='Jobtype')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reporting.printer', verbose_name='Printer')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentPrinter',
            fields=[
                ('department_printer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Department Printer ID')),
                ('jobtype_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='security.jobtype', verbose_name='Jobtype')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reporting.printer', verbose_name='Printer')),
            ],
            options={
                'verbose_name': 'Department Printer',
                'verbose_name_plural': 'Department Printers',
            },
        ),
    ]
