# Generated by Django 4.2.7 on 2025-01-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_userprinterinfo_departmentprinter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprinterinfo',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default Printer'),
        ),
    ]
