# Generated by Django 4.2.7 on 2025-02-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_alter_userprinterinfo_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentprinter',
            name='printer_path',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Printer Path'),
        ),
    ]
