# Generated by Django 4.2.7 on 2025-02-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_departmentprinter_printer_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentprinter',
            name='printer_path',
        ),
    ]
