# Generated by Django 4.2.7 on 2025-02-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
        ('security', '0014_remove_departmentprinter_printer_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentprinter',
            unique_together={('printer_id', 'jobtype_id')},
        ),
    ]
