# Generated by Django 4.2.7 on 2025-02-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_alter_departmentprinter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='siteid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='security.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='departmentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='security.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='site',
            name='timezone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='security.sitetimezone', verbose_name='Timezone'),
        ),
    ]
