# Generated by Django 4.2.7 on 2025-05-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0016_alter_department_siteid_alter_jobtype_departmentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='lab_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Lab Name'),
        ),
    ]
