# Generated by Django 4.2.7 on 2025-05-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0017_department_lab_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprinterinfo',
            name='printer_category',
            field=models.CharField(verbose_name='Print Operation Category'),
        ),
    ]
