# Generated by Django 4.2.7 on 2025-07-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0018_alter_userprinterinfo_printer_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprinterinfo',
            options={'verbose_name': 'User Printer Info', 'verbose_name_plural': 'User Printer Info'},
        ),
    ]
