# Generated by Django 4.2.7 on 2025-02-06 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0005_alter_workflowstep_workflow_id'),
        ('process', '0003_containertype_child_sample_creation'),
        ('security', '0012_alter_userprinterinfo_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0006_modalitymodelmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Sample Id')),
                ('custodial_storage_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='Custodial Storage')),
                ('previous_step', models.CharField(blank=True, max_length=40, null=True, verbose_name='Previous Step')),
                ('current_step', models.CharField(max_length=40, verbose_name='Current Step')),
                ('next_step', models.CharField(blank=True, max_length=40, null=True, verbose_name='Next Step')),
                ('avail_at', models.DateTimeField(verbose_name='Avail DateTime')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('mod_dt', models.DateTimeField(auto_now=True, verbose_name='Modified DateTime')),
                ('container_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='process.containertype', verbose_name='Container Type')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='CreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('custodial_department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='security.department', verbose_name='Custodial Department')),
                ('custodial_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='CustodialUser', to=settings.AUTH_USER_MODEL, verbose_name='Custodial User')),
                ('mod_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ModifiedBy', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('sample_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='process.sampletype', verbose_name='Sample Type')),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
            },
        ),
        migrations.CreateModel(
            name='SampleTestMap',
            fields=[
                ('sample_test_map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Sample Test Map ID')),
                ('test_status', models.CharField(max_length=50, verbose_name='Test Status')),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sample.sample', verbose_name='Sample ID')),
                ('test_id', models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.test', verbose_name='Test ID')),
                ('workflow_id', models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.RESTRICT, to='workflows.workflow', verbose_name='Workflow ID')),
            ],
            options={
                'verbose_name': 'SampleTestMap',
                'verbose_name_plural': 'SampleTestMap',
            },
        ),
    ]
