# Generated by Django 4.2.7 on 2025-02-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='accession_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='accessionsample', to='sample.sample', verbose_name='Accession Sample'),
        ),
        migrations.CreateModel(
            name='ChildSample',
            fields=[
                ('child_sample_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Child Sample ID')),
                ('destination_sample', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destinationsample', to='sample.sample', verbose_name='Child Sample ID')),
                ('source_sample', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sourcesample', to='sample.sample', verbose_name='Parent Sample ID')),
            ],
            options={
                'verbose_name': 'ChildSample',
                'verbose_name_plural': 'ChildSamples',
            },
        ),
    ]
