# Generated by Django 4.2.7 on 2025-03-03 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0016_alter_department_siteid_alter_jobtype_departmentid_and_more'),
        ('accessioning', '0003_remove_accession_is_technical_component_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sample', '0002_sample_accession_sample_childsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='accession_generated',
            field=models.BooleanField(default=False, verbose_name='Accession Generated'),
        ),
        migrations.AddField(
            model_name='sample',
            name='accession_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='AccessionID', to='accessioning.accession', verbose_name='Accession ID'),
        ),
        migrations.AddField(
            model_name='sample',
            name='collection_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Collection Date Time'),
        ),
        migrations.AddField(
            model_name='sample',
            name='pending_action',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pending Action'),
        ),
        migrations.AddField(
            model_name='sample',
            name='received_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Receive Date Time'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='avail_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Avail DateTime'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='custodial_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='security.department', verbose_name='Custodial Department'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='custodial_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CustodialUser', to=settings.AUTH_USER_MODEL, verbose_name='Custodial User'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='mod_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date Time'),
        ),
    ]
