# Generated by Django 4.2.7 on 2025-03-31 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessioning', '0004_alter_accessionicdcodemap_options_and_more'),
        ('process', '0006_containertype_gen_block_or_cassette_seq_and_more'),
        ('sample', '0003_sample_accession_generated_sample_accession_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='received_dt',
        ),
        migrations.AddField(
            model_name='sample',
            name='block_or_cassette_seq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Block/Cassette #'),
        ),
        migrations.AddField(
            model_name='sample',
            name='body_site',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Body Site'),
        ),
        migrations.AddField(
            model_name='sample',
            name='collection_dt_timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='collection_method',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Collection Method'),
        ),
        migrations.AddField(
            model_name='sample',
            name='descriptive',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descriptive'),
        ),
        migrations.AddField(
            model_name='sample',
            name='gross_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Gross Code'),
        ),
        migrations.AddField(
            model_name='sample',
            name='grossing_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Grossing Comments'),
        ),
        migrations.AddField(
            model_name='sample',
            name='isvisible',
            field=models.BooleanField(null=True, verbose_name='Is visible'),
        ),
        migrations.AddField(
            model_name='sample',
            name='num_of_blocks',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Blocks'),
        ),
        migrations.AddField(
            model_name='sample',
            name='num_of_slides',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Slides'),
        ),
        migrations.AddField(
            model_name='sample',
            name='part_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Part No'),
        ),
        migrations.AddField(
            model_name='sample',
            name='pieces',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pieces'),
        ),
        migrations.AddField(
            model_name='sample',
            name='receive_dt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Receive Date'),
        ),
        migrations.AddField(
            model_name='sample',
            name='receive_dt_timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sample Status'),
        ),
        migrations.AddField(
            model_name='sample',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='sample',
            name='slide_seq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Slide #'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='accession_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='AccessionID', to='accessioning.accession', verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='collection_dt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Collection Date'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='container_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='process.containertype', verbose_name='Container'),
        ),
        migrations.AlterField(
            model_name='sampletestmap',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.sample', verbose_name='Sample ID'),
        ),
    ]
