# Generated by Django 4.2.7 on 2025-04-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_remove_sample_received_dt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSample',
            fields=[
            ],
            options={
                'verbose_name': 'Historical Sample',
                'verbose_name_plural': 'Historical Samples',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sample.sample',),
        ),
        migrations.CreateModel(
            name='StoredSample',
            fields=[
            ],
            options={
                'verbose_name': 'Stored Sample',
                'verbose_name_plural': 'Stored Samples',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sample.sample',),
        ),
    ]
