# Generated by Django 4.2.7 on 2025-05-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_historicalsample_storedsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='smearing_process',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Smearing Process'),
        ),
    ]
