# Generated by Django 4.2.7 on 2025-05-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_sample_smearing_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='num_of_manualsmear_slides',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Manual Smear Slides'),
        ),
        migrations.AddField(
            model_name='sample',
            name='num_of_thinprep_slides',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Thin Smear Slides'),
        ),
    ]
