# Generated by Django 4.2.7 on 2025-05-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_sample_num_of_manualsmear_slides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletestmap',
            name='microtomy_completed',
            field=models.BooleanField(null=True, verbose_name='Is Microtomy Completed'),
        ),
    ]
