# Generated by Django 4.2.7 on 2025-06-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_sampletestmap_microtomy_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='label_count',
            field=models.IntegerField(default=0, verbose_name='Label Events'),
        ),
    ]
