# Generated by Django 4.2.7 on 2025-07-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_sample_label_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='gross_description',
            field=models.TextField(blank=True, null=True, verbose_name='Gross Description'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sub_site',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Sub Site'),
        ),
    ]
