# Generated by Django 4.2.7 on 2025-08-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_sample_gross_description_sample_sub_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletestmap',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sample.sample', verbose_name='Sample ID'),
        ),
    ]
