# Generated by Django 4.2.7 on 2025-09-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_alter_workflow_accession_type'),
        ('sample', '0011_alter_sampletestmap_sample_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='workflow_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='workflows.workflow', verbose_name='Workflow Id'),
        ),
    ]
