# Generated by Django 4.2.7 on 2025-01-28 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('printer_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Printer ID')),
                ('printer_name', models.CharField(max_length=80, verbose_name='Printer Name')),
                ('printer_path', models.CharField(max_length=120, verbose_name='Printer Path')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Printer',
                'verbose_name_plural': 'Printers',
            },
        ),
        migrations.CreateModel(
            name='LabelMethod',
            fields=[
                ('label_method_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Label Method Id')),
                ('label_method_name', models.CharField(max_length=40, verbose_name='Label Method Name')),
                ('label_method_version_id', models.IntegerField(verbose_name='Label Method Version Id')),
                ('label_method_desc', models.CharField(max_length=80, verbose_name='Label Method Desc')),
                ('export_location', models.CharField(max_length=255, verbose_name='Export Location')),
                ('designer_format', models.CharField(max_length=80, verbose_name='Designer Format')),
                ('label_query', models.TextField(verbose_name='Label Query')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Label Method',
                'verbose_name_plural': 'Label Methods',
                'unique_together': {('label_method_name', 'label_method_version_id')},
            },
        ),
    ]
