# Generated by Django 4.2.7 on 2025-03-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_alter_labelmethod_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelmethod',
            name='api_driven',
            field=models.BooleanField(default=False, help_text='Enable this to print via API. No dd files generated.', verbose_name='API Driven'),
        ),
        migrations.AddField(
            model_name='labelmethod',
            name='s3bucket',
            field=models.BooleanField(default=False, help_text='Enable this to store label files in S3 Bucket. Mention the bucket path in <b>Export Location</b> field below', verbose_name='S3 Bucket?'),
        ),
        migrations.AlterField(
            model_name='labelmethod',
            name='export_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Export Location'),
        ),
    ]
