# Generated by Django 4.2.7 on 2025-04-25 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_containertype_gen_block_or_cassette_seq_and_more'),
        ('reporting', '0004_labelmethod_api_driven_labelmethod_s3bucket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelmethod',
            name='api_driven',
        ),
        migrations.AddField(
            model_name='labelmethod',
            name='delimiter',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Delimiter'),
        ),
        migrations.AddField(
            model_name='labelmethod',
            name='file_format',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Label File Format'),
        ),
        migrations.AddField(
            model_name='printer',
            name='communication_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Communication Type'),
        ),
        migrations.CreateModel(
            name='ContainerTypeLabelMethodMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='label_methods', to='process.containertype', verbose_name='Container Type')),
                ('label_method', models.ForeignKey(help_text='Select a label method name and version', on_delete=django.db.models.deletion.RESTRICT, to='reporting.labelmethod', verbose_name='Label Method')),
            ],
            options={
                'verbose_name': 'Container Type - Label Method Mapping',
                'verbose_name_plural': 'Container Type - Label Method Mappings',
                'unique_together': {('container_type', 'label_method')},
            },
        ),
    ]
