# Generated by Django 4.2.7 on 2025-05-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_remove_labelmethod_api_driven_labelmethod_delimiter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelmethod',
            name='show_fields',
            field=models.BooleanField(default=False, help_text='Enable this for File Based BarTender Printing', verbose_name='Show Field Names in Label File'),
        ),
        migrations.AddField(
            model_name='labelmethod',
            name='show_header',
            field=models.BooleanField(default=False, help_text='Enable this for File Based BarTender Printing', verbose_name='Show Header in Label File'),
        ),
    ]
