# Generated by Django 4.2.7 on 2025-12-01 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_containertype_workflow_id'),
        ('reporting', '0006_labelmethod_show_fields_labelmethod_show_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelmethod',
            name='is_bio_pharma_label',
            field=models.BooleanField(default=False, verbose_name='Is Pharma Label?'),
        ),
        migrations.AlterField(
            model_name='labelmethod',
            name='designer_format',
            field=models.CharField(max_length=200, verbose_name='Designer Format'),
        ),
        migrations.CreateModel(
            name='ContainerTypePharmaLabelMethodMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pharma_label_methods', to='process.containertype', verbose_name='Container Type')),
                ('label_method', models.ForeignKey(help_text='Select a BioPharma label method name and version', on_delete=django.db.models.deletion.RESTRICT, to='reporting.labelmethod', verbose_name='BioPharma Label Method')),
            ],
            options={
                'verbose_name': 'Container Type - Pharma Label Method Mapping',
                'verbose_name_plural': 'Container Type - Pharma Label Method Mappings',
                'unique_together': {('container_type', 'label_method')},
            },
        ),
    ]
