# Generated by Django 4.2.7 on 2025-03-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample', '0002_sample_accession_sample_childsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='CytoWorkflow',
            fields=[
                ('sample_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sample.sample')),
                ('stain_date', models.DateTimeField(blank=True, null=True, verbose_name='Stain DateTime')),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
            },
            bases=('sample.sample',),
        ),
    ]
