# Generated by Django 4.2.7 on 2025-03-31 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cytoworkflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cytoworkflow',
            options={'verbose_name': 'Cyto Sample', 'verbose_name_plural': 'Cyto Samples'},
        ),
    ]
