# Generated by Django 4.2.7 on 2025-07-14 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accessioning', '0008_accession_is_template'),
        ('security', '0019_alter_userprinterinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalProfessionalComponentMap',
            fields=[
                ('technical_professional_component_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('component_type', models.CharField(choices=[('TC', 'Technical Component'), ('TCA', 'Technical Component with Assistance'), ('PC', 'Professional Component')], max_length=3, verbose_name='Component Type')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime')),
                ('mod_dt', models.DateTimeField(auto_now=True, verbose_name='Modified Date Time')),
                ('accession_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accessioning.accession', verbose_name='Accession ID')),
                ('compontent_site_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='security.site', verbose_name='Component Site ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tpcmcreated_by', to=settings.AUTH_USER_MODEL, verbose_name='TPCMCreated By')),
                ('mod_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='TPCMModifiedBy', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'TechnicalProfessionalComponentMap',
                'verbose_name_plural': 'TechnicalProfessionalComponentMaps',
                'unique_together': {('technical_professional_component_map_id', 'accession_id', 'compontent_site_id', 'component_type')},
            },
        ),
    ]
