# Generated by Django 4.2.7 on 2025-08-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accessioning', '0008_accession_is_template'),
        ('analysis', '0009_alter_reportoption_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessionHistoricalReportsWrapper',
            fields=[
            ],
            options={
                'verbose_name': 'Historical Case',
                'verbose_name_plural': 'Historical Cases',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accessioning.accession',),
        ),
        migrations.CreateModel(
            name='AccessionReportsWrapper',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Case',
                'verbose_name_plural': 'Pending Cases',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accessioning.accession',),
        ),
        migrations.CreateModel(
            name='AttachmentMergeReport',
            fields=[
            ],
            options={
                'verbose_name': 'Signed Report',
                'verbose_name_plural': 'Signed Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analysis.attachment',),
        ),
    ]
