# Generated by Django 4.2.7 on 2025-07-07 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accessioning', '0008_accession_is_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessionTemplate',
            fields=[
            ],
            options={
                'verbose_name': 'Accession Template',
                'verbose_name_plural': 'Accession Templates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accessioning.accession',),
        ),
        migrations.CreateModel(
            name='PathologyTemplate',
            fields=[
                ('pathology_temp_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Pathology Template Id')),
                ('dx_code', models.CharField(max_length=80, unique=True, verbose_name='Diagnosis Code')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnosis')),
                ('microscopic_desc', models.TextField(blank=True, null=True, verbose_name='Microscopic Desc')),
                ('category', models.CharField(blank=True, max_length=80, null=True, verbose_name='Category')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Pathology Template',
                'verbose_name_plural': 'Pathology Templates',
            },
        ),
        migrations.CreateModel(
            name='GrossCodeTemplate',
            fields=[
                ('gross_code_temp_id', models.AutoField(primary_key=True, serialize=False, verbose_name='GrossCode Template Id')),
                ('gross_code', models.CharField(max_length=80, unique=True, verbose_name='Gross Code')),
                ('gross_description', models.TextField(blank=True, null=True, verbose_name='Gross Description')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'GrossCode Template',
                'verbose_name_plural': 'GrossCode Templates',
            },
        ),
    ]
