# Generated by Django 4.2.7 on 2025-10-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessioning', '0010_biopharmaaccession_investigator_and_more'),
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioPharmaAccessionTemplate',
            fields=[
            ],
            options={
                'verbose_name': 'Pharma Accession Template',
                'verbose_name_plural': 'Pharma Accession Templates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accessioning.biopharmaaccession',),
        ),
    ]
