# Generated by Django 4.2.7 on 2025-12-01 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('template', '0002_biopharmaaccessiontemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macros',
            fields=[
                ('macros_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Macros Id')),
                ('macros_name', models.CharField(max_length=40, unique=True, verbose_name='Macros Name')),
                ('actual_content', models.TextField(blank=True, null=True, verbose_name='Actual Content')),
                ('macros_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Macros Type')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Macros',
                'verbose_name_plural': 'Macros',
            },
        ),
    ]
