# Generated by Django 4.2.7 on 2025-01-20 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('instrument_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Instrument Type Id')),
                ('instrument_type', models.CharField(max_length=40, unique=True, verbose_name='Instrument Type')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Instrument Type',
                'verbose_name_plural': 'Instrument Types',
            },
        ),
        migrations.CreateModel(
            name='InstrumentModel',
            fields=[
                ('instrument_model_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Instrument Model Id')),
                ('instrument_model', models.CharField(max_length=40, verbose_name='Instrument Model')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('instrument_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labresource.instrumenttype', verbose_name='Instrument Type')),
            ],
            options={
                'verbose_name': 'Instrument Model',
                'verbose_name_plural': 'Instrument Models',
                'unique_together': {('instrument_model', 'instrument_type')},
            },
        ),
    ]
