# Generated by Django 4.2.7 on 2025-01-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labresource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentmodel',
            name='instrument_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labresource.instrumenttype', verbose_name='Instrument Type'),
        ),
    ]
