# Generated by Django 4.2.7 on 2025-02-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labresource', '0002_alter_instrumentmodel_instrument_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentmodel',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime'),
        ),
    ]
