# Generated by Django 4.2.7 on 2025-02-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labresource', '0003_alter_instrumentmodel_created_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentmodel',
            name='instrument_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='labresource.instrumenttype', verbose_name='Instrument Type'),
        ),
    ]
