# Generated by Django 4.2.7 on 2025-04-19 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0018_delete_modalitymodelmap'),
        ('sample', '0005_historicalsample_storedsample'),
        ('accessioning', '0006_alter_accession_accession_type_delete_accessiontype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportOption',
            fields=[
                ('report_option_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Report Option ID')),
                ('version_id', models.IntegerField()),
                ('amendment_type', models.CharField(blank=True, max_length=40, null=True, verbose_name='Amendment Type')),
                ('reporting_status', models.CharField(max_length=40, verbose_name='Reporting Status')),
                ('current_step', models.CharField(blank=True, max_length=40, null=True, verbose_name='Current Step')),
                ('pending_action', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pending Action')),
                ('accession_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accessioning.accession', verbose_name='Accession ID')),
                ('assign_pathologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Assigned Pathologist')),
                ('root_sample_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sample.sample', verbose_name='Root Sample ID')),
                ('test_id', models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.test', verbose_name='Test ID')),
            ],
            options={
                'verbose_name': 'ReportOption',
                'verbose_name_plural': 'ReportOptions',
                'unique_together': {('report_option_id', 'accession_id', 'root_sample_id', 'version_id')},
            },
        ),
        migrations.CreateModel(
            name='ReportOptionDtl',
            fields=[
                ('report_option_dtl_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Report Option Detail ID')),
                ('version_id', models.IntegerField()),
                ('analyte_value', models.TextField(blank=True, null=True, verbose_name='Analyte Value')),
                ('accession_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accessioning.accession', verbose_name='Accession ID')),
                ('analyte_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tests.analyte', verbose_name='Analyte ID')),
                ('report_option_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='analysis.reportoption', verbose_name='Report Option ID')),
                ('root_sample_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sample.sample', verbose_name='Root Sample ID')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tests.test', verbose_name='Test ID')),
            ],
            options={
                'verbose_name': 'ReportOptionDtl',
                'verbose_name_plural': 'ReportOptionDtls',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Attachment ID')),
                ('version_id', models.IntegerField()),
                ('report_filepath', models.CharField(blank=True, max_length=100, null=True, verbose_name='Report File Path')),
                ('report_option_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='analysis.reportoption', verbose_name='Report Option ID')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
