# Generated by Django 4.2.7 on 2025-05-03 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_delete_modalitymodelmap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportoption',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='reportoptiondtl',
            options={'verbose_name': 'Report Detail', 'verbose_name_plural': 'Report Details'},
        ),
        migrations.AddField(
            model_name='reportoption',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='reportoption',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime'),
        ),
        migrations.AddField(
            model_name='reportoptiondtl',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='reportoptiondtl',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='reportoption',
            name='assign_pathologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assign_pathologist', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Pathologist'),
        ),
        migrations.AlterField(
            model_name='reportoptiondtl',
            name='analyte_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tests.analyte', verbose_name='Analyte'),
        ),
    ]
