# Generated by Django 4.2.7 on 2025-05-28 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_testanalyte_is_reportable_and_more'),
        ('sample', '0008_sampletestmap_microtomy_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0018_alter_userprinterinfo_printer_category'),
        ('accessioning', '0006_alter_accession_accession_type_delete_accessiontype'),
        ('analysis', '0002_alter_reportoption_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReportOption',
            fields=[
            ],
            options={
                'verbose_name': 'Historical Report',
                'verbose_name_plural': 'Historical Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analysis.reportoption',),
        ),
        migrations.AddField(
            model_name='attachment',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created DateTime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='mod_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='AtchmntModifiedBy', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='mod_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date Time'),
        ),
        migrations.AddField(
            model_name='reportoption',
            name='avail_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Avail DateTime'),
        ),
        migrations.AddField(
            model_name='reportoption',
            name='custodial_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='security.department', verbose_name='Custodial Department'),
        ),
        migrations.AddField(
            model_name='reportoption',
            name='last_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='last_signed_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Signed By'),
        ),
        migrations.AddField(
            model_name='reportoption',
            name='last_signed_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Signed DateTime'),
        ),
        migrations.AddField(
            model_name='reportoption',
            name='mod_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='ROModifiedBy', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportoption',
            name='mod_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date Time'),
        ),
        migrations.AddField(
            model_name='reportoption',
            name='next_step',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Next Step'),
        ),
        migrations.AddField(
            model_name='reportoption',
            name='previous_step',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Previous Step'),
        ),
        migrations.AddField(
            model_name='reportoptiondtl',
            name='mod_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='RODModifiedBy', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportoptiondtl',
            name='mod_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date Time'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Attachment ID'),
        ),
        migrations.AlterField(
            model_name='reportoption',
            name='report_option_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Report Option ID'),
        ),
        migrations.AlterField(
            model_name='reportoptiondtl',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportoptiondtl',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created DateTime'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportoptiondtl',
            name='report_option_dtl_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Report Option Detail ID'),
        ),
        migrations.CreateModel(
            name='ReportSignOut',
            fields=[
                ('report_sign_out_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Report Sign Out ID')),
                ('version_id', models.IntegerField()),
                ('analyte_value', models.TextField(blank=True, null=True, verbose_name='Analyte Value')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('mod_dt', models.DateTimeField(auto_now=True, verbose_name='Modified Date Time')),
                ('accession_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accessioning.accession', verbose_name='Accession ID')),
                ('analyte_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tests.analyte', verbose_name='Analyte')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mod_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='RSOModifiedBy', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('report_option_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='analysis.reportoption', verbose_name='Report Option ID')),
                ('root_sample_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sample.sample', verbose_name='Root Sample ID')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tests.test', verbose_name='Test ID')),
            ],
            options={
                'verbose_name': 'Report Sign Out',
                'verbose_name_plural': 'Report Sign Outs',
            },
        ),
    ]
