# Generated by Django 4.2.7 on 2025-05-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_historicalreportoption_attachment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='report_filepath',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Report File Path'),
        ),
    ]
