# Generated by Django 4.2.7 on 2025-06-10 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessioning', '0007_accession_label_count'),
        ('sample', '0009_sample_label_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0021_testanalyte_is_reportable_and_more'),
        ('analysis', '0004_alter_attachment_report_filepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeReporting',
            fields=[
                ('merge_reporting_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Merge Reporting ID')),
                ('amendment_type', models.CharField(blank=True, max_length=40, null=True, verbose_name='Amendment Type')),
                ('reporting_status', models.CharField(max_length=40, verbose_name='Reporting Status')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('mod_dt', models.DateTimeField(auto_now=True, verbose_name='Modified Date Time')),
                ('last_signed_dt', models.DateTimeField(blank=True, null=True, verbose_name='Last Signed DateTime')),
                ('accession_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accessioning.accession', verbose_name='Accession ID')),
                ('assign_pathologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mr_assign_pathologist', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Pathologist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mr_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mr_last_signed_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Signed By')),
                ('mod_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mr_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Merge Reporting',
                'verbose_name_plural': 'Merge Reporting',
            },
        ),
        migrations.RemoveField(
            model_name='reportoptiondtl',
            name='accession_id',
        ),
        migrations.RemoveField(
            model_name='reportoptiondtl',
            name='root_sample_id',
        ),
        migrations.RemoveField(
            model_name='reportoptiondtl',
            name='test_id',
        ),
        migrations.AlterField(
            model_name='reportsignout',
            name='accession_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='accessioning.accession', verbose_name='Accession ID'),
        ),
        migrations.AlterField(
            model_name='reportsignout',
            name='root_sample_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sample.sample', verbose_name='Root Sample ID'),
        ),
        migrations.AlterField(
            model_name='reportsignout',
            name='test_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.test', verbose_name='Test ID'),
        ),
        migrations.CreateModel(
            name='MergeReportingDtl',
            fields=[
                ('merge_reporting_dtl_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Merge Reporting Detail ID')),
                ('analyte_value', models.TextField(blank=True, null=True, verbose_name='Analyte Value')),
                ('version_id', models.IntegerField()),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('mod_dt', models.DateTimeField(auto_now=True, verbose_name='Modified Date Time')),
                ('analyte_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tests.analyte', verbose_name='Analyte')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mrd_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('merge_reporting_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='analysis.mergereporting', verbose_name='Merge Reporting ID')),
                ('mod_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mrd_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('report_option_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='analysis.reportoption', verbose_name='Report Option ID')),
            ],
            options={
                'verbose_name': 'Merge Reporting Detail',
                'verbose_name_plural': 'Merge Reporting Details',
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='merge_reporting_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='analysis.mergereporting', verbose_name='Merge Reporting ID'),
        ),
        migrations.AddField(
            model_name='reportsignout',
            name='merge_reporting_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='analysis.mergereporting', verbose_name='Merge Reporting ID'),
        ),
    ]
