# Generated by Django 4.2.7 on 2025-07-07 11:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accessioning', '0008_accession_is_template'),
        ('masterdata', '0007_bodysite_alter_client_name_reportimgpropinfo_and_more'),
        ('analysis', '0005_mergereporting_remove_reportoptiondtl_accession_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMergeReporting',
            fields=[
            ],
            options={
                'verbose_name': 'Historical Merge Reporting',
                'verbose_name_plural': 'Historical Merge Reporting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analysis.mergereporting',),
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='report_filepath',
        ),
        migrations.AddField(
            model_name='attachment',
            name='accession_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='accessioning.accession', verbose_name='Accession ID'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Attachment Type'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.client', verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_path',
            field=models.FileField(default=django.utils.timezone.now, max_length=2000, upload_to='', verbose_name='File Path'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='physician_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.physician', verbose_name='Physician ID'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='version_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Version Id'),
        ),
    ]
