# Generated by Django 4.2.7 on 2025-07-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_historicalmergereporting_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmergereporting',
            options={'verbose_name': 'Reporting', 'verbose_name_plural': 'Reporting'},
        ),
        migrations.AlterModelOptions(
            name='mergereporting',
            options={'verbose_name': 'Reporting', 'verbose_name_plural': 'Reporting'},
        ),
    ]
