# Generated by Django 4.2.7 on 2025-07-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessioning', '0008_accession_is_template'),
        ('analysis', '0007_alter_historicalmergereporting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergereporting',
            name='accession_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accessioning.accession', verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='reportoption',
            name='accession_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accessioning.accession', verbose_name='Case Number'),
        ),
    ]
