# Generated by Django 4.2.7 on 2025-08-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessioning', '0008_accession_is_template'),
        ('sample', '0011_alter_sampletestmap_sample_id'),
        ('analysis', '0008_alter_mergereporting_accession_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportoption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mergereporting',
            name='methodology',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Methodology'),
        ),
        migrations.AddField(
            model_name='reportoption',
            name='methodology',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Methodology'),
        ),
        migrations.AlterUniqueTogether(
            name='reportoption',
            unique_together={('report_option_id', 'accession_id', 'root_sample_id', 'version_id', 'methodology')},
        ),
    ]
