# Generated by Django 4.2.7 on 2025-10-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_workflowstep_backward_movement'),
        ('analysis', '0009_alter_reportoption_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportoption',
            name='workflow_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='workflows.workflow', verbose_name='Workflow Id'),
        ),
    ]
