# Generated by Django 4.2.7 on 2025-12-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_reportoption_workflow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergereporting',
            name='amendment_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Amendment Comments'),
        ),
    ]
