# Generated by Django 4.2.7 on 2025-02-02 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0012_alter_userprinterinfo_is_default'),
        ('masterdata', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('accession_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Accession_Id')),
                ('active_flag', models.CharField(default='Y', max_length=10, null=True, verbose_name='Active Flag')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('accession_lab', models.CharField(blank=True, max_length=50, null=True, verbose_name='Accession Lab')),
                ('status', models.CharField(blank=True, max_length=40, null=True, verbose_name='Status')),
                ('complete_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Completed DateTime')),
                ('qc_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='QC DateTime')),
                ('env_type', models.CharField(blank=True, default='Clinical', max_length=50, null=True, verbose_name='Env Type')),
                ('diagnosis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Diagnosis')),
                ('accession_type', models.CharField(max_length=40, null=True, verbose_name='Accession_Type')),
                ('accession_template', models.CharField(max_length=40, null=True, verbose_name='Accession Template')),
                ('accession_prefix', models.CharField(blank=True, max_length=10, null=True, verbose_name='Accession Prefix')),
                ('payment_type', models.CharField(max_length=40, null=True, verbose_name='Payment Type')),
                ('is_external', models.BooleanField(default=False, verbose_name='External')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Internal')),
                ('is_technical_component', models.BooleanField(default=False, verbose_name='Technical Component')),
                ('is_auto_gen_pk', models.BooleanField(default=True, verbose_name='Auto Key Generation')),
                ('accession_failedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acc_failed_by', to=settings.AUTH_USER_MODEL, verbose_name='Accession Failed By')),
                ('accessionqc_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acc_qc_by', to=settings.AUTH_USER_MODEL, verbose_name='Accession QC By')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('created_by_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='security.department', verbose_name='Created By Dept')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.physician', verbose_name='Referring Doctor')),
                ('insurance_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.patientinsuranceinfo', verbose_name='Insurance')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Accessioning',
                'verbose_name_plural': 'Accessioning',
            },
        ),
    ]
