# Generated by Django 4.2.7 on 2025-02-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_alter_client_created_dt_and_more'),
        ('accessioning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='complete_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Completed DateTime'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='qc_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='QC DateTime'),
        ),
    ]
