# Generated by Django 4.2.7 on 2025-03-03 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_alter_testattribute_unique_together_and_more'),
        ('masterdata', '0003_client_fax_number_alter_client_client_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accessioning', '0002_alter_accession_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accession',
            name='is_technical_component',
        ),
        migrations.AddField(
            model_name='accession',
            name='is_technical_reporting',
            field=models.BooleanField(default=False, verbose_name='Technical Reporting'),
        ),
        migrations.AddField(
            model_name='accession',
            name='reporting_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporting_doctor', to='masterdata.physician', verbose_name='Reporting Doctor'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='accession_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Accession ID'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='accession_type',
            field=models.CharField(max_length=40, null=True, verbose_name='Accession Type'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='complete_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Completed Date Time'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='qc_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='QC Date Time'),
        ),
        migrations.CreateModel(
            name='AccessionICDCodeMap',
            fields=[
                ('accession_icd_code_map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Accession ICD Code Map ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('mod_dt', models.DateTimeField(auto_now=True, verbose_name='Modified Date Time')),
                ('accession_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accessioning.accession', verbose_name='Accession ID')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ICDCodeCreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('icd_code_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tests.icdcode', verbose_name='ICD Code')),
                ('mod_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ICDCodeModifiedBy', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'AccessionICDCodeMap',
                'verbose_name_plural': 'AccessionICDCodeMaps',
            },
        ),
        migrations.AddConstraint(
            model_name='accessionicdcodemap',
            constraint=models.UniqueConstraint(fields=('accession_id', 'icd_code_id'), name='unique_accession_id_icd_code_id'),
        ),
    ]
