# Generated by Django 4.2.7 on 2025-03-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessioning', '0003_remove_accession_is_technical_component_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessionicdcodemap',
            options={'verbose_name': 'ICD Code', 'verbose_name_plural': 'ICD Code'},
        ),
        migrations.AddField(
            model_name='accession',
            name='collection_dt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Collection Date'),
        ),
        migrations.AddField(
            model_name='accession',
            name='collection_dt_timezone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Collection Date Timezone'),
        ),
        migrations.AddField(
            model_name='accession',
            name='receive_dt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Receive Date'),
        ),
        migrations.AddField(
            model_name='accession',
            name='receive_dt_timezone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Receive Date Timezone'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='accession_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Case Number'),
        ),
    ]
