# Generated by Django 4.2.7 on 2025-04-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessioning', '0004_alter_accessionicdcodemap_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessionType',
            fields=[
                ('accession_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Accession Type Id')),
                ('accession_type', models.CharField(max_length=20, unique=True, verbose_name='Accession Type')),
                ('reporting_type', models.CharField(blank=True, choices=[('internal', 'Internal'), ('external', 'External')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'AccessionType',
                'verbose_name_plural': 'AccessionTypes',
            },
        ),
        migrations.AddField(
            model_name='accession',
            name='accession_category',
            field=models.CharField(max_length=40, null=True, verbose_name='Accession Category'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='accession_type',
            field=models.ForeignKey(max_length=40, null=True, on_delete=django.db.models.deletion.RESTRICT, to='accessioning.accessiontype', verbose_name='Accession Type'),
        ),
    ]
