# Generated by Django 4.2.7 on 2025-04-19 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_accessiontype'),
        ('workflows', '0009_alter_workflow_accession_type_modalitymodelmap'),
        ('accessioning', '0005_accessiontype_accession_accession_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='accession_type',
            field=models.ForeignKey(max_length=40, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.accessiontype', verbose_name='Accession Type'),
        ),
        migrations.DeleteModel(
            name='AccessionType',
        ),
    ]
