# Generated by Django 4.2.7 on 2025-06-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessioning', '0006_alter_accession_accession_type_delete_accessiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='label_count',
            field=models.IntegerField(default=0, verbose_name='Label Events'),
        ),
    ]
