# Generated by Django 4.2.7 on 2025-07-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessioning', '0007_accession_label_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='is_template',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Template'),
        ),
    ]
