# Generated by Django 4.2.7 on 2025-09-26 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessioning', '0008_accession_is_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioPharmaAccession',
            fields=[
                ('accession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accessioning.accession')),
            ],
            options={
                'verbose_name': 'Pharma Accession',
                'verbose_name_plural': 'Pharma Accessions',
            },
            bases=('accessioning.accession',),
        ),
    ]
