# Generated by Django 4.2.7 on 2025-09-26 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessioning', '0009_biopharmaaccession'),
        ('masterdata', '0008_bioproject_subject_sponsor_projectvisitmap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biopharmaaccession',
            name='investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='biopharma_accessions', to='masterdata.biosite', verbose_name='Investigator'),
        ),
        migrations.AddField(
            model_name='biopharmaaccession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='biopharma_accessions', to='masterdata.bioproject', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='biopharmaaccession',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='biopharma_accessions', to='masterdata.sponsor', verbose_name='Sponsor'),
        ),
        migrations.AddField(
            model_name='biopharmaaccession',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='biopharma_accessions', to='masterdata.projectvisitmap', verbose_name='Visit'),
        ),
    ]
