# Generated by Django 4.2.7 on 2025-12-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_alter_patient_city_alter_patient_mrn_and_more'),
        ('accessioning', '0010_biopharmaaccession_investigator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='reporting_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporting_doctor', to='masterdata.physician', verbose_name='Reporting Doctor / Pathologist'),
        ),
    ]
