# Generated by Django 4.2.7 on 2025-01-20 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0007_jobtype_site_independent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('workflow_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Workflow')),
                ('workflow_name', models.CharField(max_length=40, verbose_name='Workflow Name')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('methodology', models.CharField(blank=True, max_length=200, null=True, verbose_name='Methodology')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflow',
                'unique_together': {('workflow_name', 'methodology')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('workflow_step_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Workflow Step Id')),
                ('step_id', models.CharField(max_length=200, verbose_name='Step Id')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.department', verbose_name='Department Id')),
                ('workflow_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Workflow Step',
                'verbose_name_plural': 'Workflow Steps',
                'unique_together': {('workflow_id', 'step_id', 'department_id')},
            },
        ),
    ]
