# Generated by Django 4.2.7 on 2025-01-22 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_sitetimezone_description'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='step_id',
            field=models.CharField(max_length=200, verbose_name='Step'),
        ),
    ]
