# Generated by Django 4.2.7 on 2025-01-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_site_abbreviation'),
        ('workflows', '0002_alter_workflowstep_department_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='step_no',
            field=models.IntegerField(default=0, verbose_name='Step Number'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow_id', 'step_id', 'step_no', 'department_id')},
        ),
    ]
