# Generated by Django 4.2.7 on 2025-01-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_workflowstep_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='department',
            field=models.CharField(default=0, max_length=80, verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow_id', 'step_id', 'step_no', 'department')},
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='department_id',
        ),
    ]
