# Generated by Django 4.2.7 on 2025-01-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_alter_workflowstep_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='workflow_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow', verbose_name='Workflow'),
        ),
    ]
