# Generated by Django 4.2.7 on 2025-02-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_alter_workflowstep_workflow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='workflow_type',
            field=models.CharField(blank=True, choices=[('WetLab', 'Wet Lab'), ('DryLab', 'Dry lab')], max_length=40, null=True, verbose_name='Workflow Type'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime'),
        ),
    ]
