# Generated by Django 4.2.7 on 2025-02-06 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0006_workflowstep_workflow_type_alter_workflow_created_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='workflow_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='workflows.workflow', verbose_name='Workflow'),
        ),
    ]
