# Generated by Django 4.2.7 on 2025-04-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessioning', '0005_accessiontype_accession_accession_category_and_more'),
        ('workflows', '0007_alter_workflow_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='accession_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='accessioning.accessiontype', verbose_name='AccessionType'),
        ),
    ]
