# Generated by Django 4.2.7 on 2025-04-19 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0005_accessiontype'),
        ('workflows', '0008_workflow_accession_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='accession_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.accessiontype', verbose_name='AccessionType'),
        ),
        migrations.CreateModel(
            name='ModalityModelMap',
            fields=[
                ('modality_model_map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Modality Model Map ID')),
                ('modality', models.CharField(max_length=40, verbose_name='Modality')),
                ('model', models.CharField(max_length=40, verbose_name='Model')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Modality Model Map',
                'verbose_name_plural': 'Modality Model Maps',
                'unique_together': {('modality', 'model')},
            },
        ),
    ]
