# Generated by Django 4.2.7 on 2025-05-28 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_patient_middle_initial'),
        ('workflows', '0009_alter_workflow_accession_type_modalitymodelmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='accession_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.accessiontype', verbose_name='AccessionType'),
            preserve_default=False,
        ),
    ]
