# Generated by Django 4.2.7 on 2025-09-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_alter_workflow_accession_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='backward_movement',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, null=True, verbose_name='Backward Movement'),
        ),
    ]
