# Generated by Django 4.2.7 on 2025-12-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_alter_patient_city_alter_patient_mrn_and_more'),
        ('workflows', '0011_workflowstep_backward_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='accession_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.accessiontype', verbose_name='AccessionType'),
        ),
    ]
