"""
Django settings for controllerapp project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import socket
from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r5t_&nybh9r@ep@+*v)n@-s3#eeud-+42!cjbvjov!zw*%-2=_'
BUILD_NUMBER = '1.0.0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'admin_tools_stats',
    'django_nvd3',
    'rangefilter',
    'csp',
    'django_summernote',
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'logutil',
    'controllerapp',
    'auditlog',
    'audit',
    'django_celery_results',
    'django_celery_beat',
    'import_export',
    'security',
    'configuration',
    'tests',
    'process',
    'labresource',
    'workflows',
    'reporting',
    'util',
    'accessioning',
    'masterdata',
    'sample',
    'routinginfo',
    'ihcworkflow',
    'cytoworkflow',
    'analysis',
    'wetlabworklist',
    'analysisworklist',
    'template',
    'tpcm',
    'restapi',
    'channels',
    'scanner'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'security.middleware.TimezoneMiddleware',
    'logutil.middleware.ResetThreadSeqMiddleware',
]

ROOT_URLCONF = 'controllerapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auto_logout.context_processors.auto_logout_client',
            ],
        },
    },
]

WSGI_APPLICATION = 'controllerapp.wsgi.application'
ASGI_APPLICATION = 'controllerapp.asgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'gulflims',
        'USER': 'postgres',
        'PASSWORD': 'Mnop@1234',
        'HOST': 'localhost'
    }
}

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}


CACHE_TIMEOUT = 300  # 5 minutes

# Use cache-backed sessions
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
# Set session cookie age to 15 minutes (15 minutes * 60 seconds)
SESSION_COOKIE_AGE = 900
SESSION_CUSTOM_COOKIE_AGE = 300
SESSION_SAVE_EVERY_REQUEST = True

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators


# ==========================================================
# Toggle for developer verbose logging
# ==========================================================
DEBUG_LOG_SETTINGS = False
DEBUG_LOGGING = os.getenv("DEBUG_LOGGING")

if DEBUG_LOGGING is None:
    # If not set, fall back to Django's DEBUG flag
    DEBUG_LOGGING = DEBUG_LOG_SETTINGS
else:
    # If set, normalize it
    DEBUG_LOGGING = DEBUG_LOGGING.strip().lower() == "true"

LOG_LEVEL = "DEBUG" if DEBUG_LOGGING else "INFO"

LOG_APP_DIR = os.path.join(BASE_DIR, 'log/app')
LOG_APP_ERROR_DIR = os.path.join(BASE_DIR, 'log/app/error')
LOG_APP_SQL_DIR = os.path.join(BASE_DIR, 'log/app/sql')
os.makedirs(LOG_APP_DIR, exist_ok=True)
os.makedirs(LOG_APP_ERROR_DIR, exist_ok=True)
os.makedirs(LOG_APP_SQL_DIR, exist_ok=True)

# Per-node log filename using hostname
hostname = socket.gethostname()
APP_LOG_FILE = f"gulflims_{hostname}_app.log"
APP_ERROR_LOG_FILE = f"gulflims_{hostname}_error.log"
APP_SQL_LOG_FILE = f"gulflims_{hostname}_sql.log"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "filters": {
        "thread_seq_filter": {
            "()": "logutil.thread_seq_filter.ThreadSequenceFilter",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },

    "formatters": {
        "verbose": {
            "()": "logutil.formatter.MilliFormatter",
            "format": "[{asctime}][{levelname}][TID_{thread}] {name}.{funcName}() :: {message}",
            "style": "{",
            "datefmt": "%d-%b-%Y %H:%M:%S,%f",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["thread_seq_filter"],
            "stream": "ext://sys.stdout",
        },

        "gulflims_file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_APP_DIR, APP_LOG_FILE),  # Per-node log file
            "maxBytes": 100 * 1024 * 1024,  # 100 MB
            "backupCount": 10,
            "formatter": "verbose",
            "filters": ["thread_seq_filter"],
            "encoding": "utf-8",
            "delay": True,
        },

        "gulflims_file_error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_APP_ERROR_DIR, APP_ERROR_LOG_FILE),
            "maxBytes": 100 * 1024 * 1024,
            "backupCount": 10,
            "formatter": "verbose",
            "filters": ["thread_seq_filter"],
            "encoding": "utf-8",
            "delay": True,
        },

        "gulflims_file_sql": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_APP_SQL_DIR, APP_SQL_LOG_FILE),
            "maxBytes": 100 * 1024 * 1024,
            "backupCount": 10,
            "formatter": "verbose",
            "filters": ["thread_seq_filter"],
            "encoding": "utf-8",
            "delay": True,
        },

        "info": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "log/info/info.log"),
            "maxBytes": 1024 * 1024 * 300,
            "backupCount": 5,
            "formatter": "verbose",
            "filters": ["thread_seq_filter"],
            "encoding": "utf-8",
            "delay": True,
        },
        "error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "log/error/error.log"),
            "maxBytes": 1024 * 1024 * 300,
            "backupCount": 5,
            "formatter": "verbose",
            "filters": ["thread_seq_filter"],
            "encoding": "utf-8",
            "delay": True,
        }
    },

    "root": {
        "handlers": ["console", "gulflims_file", "gulflims_file_error"],
        "level": LOG_LEVEL,
    },

    "loggers": {
        "django": {
            "handlers": ["console", "gulflims_file", "gulflims_file_error", "info"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "error_log": {
            "handlers": ["error"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["gulflims_file", "gulflims_file_sql"],
            "level": "DEBUG",
            "propagate": False,
        },
    }
}

# === CUSTOMLOGGER CONFIG ===
APPLICATION_NAME = "application"

# Master switch — set to False to disable all customlogger wrapping
CUSTOMLOGGER_ENABLED = True

# Sampling — 1.0 = log every wrapped call, 0.1 = ~10% of calls
CUSTOMLOGGER_SAMPLE_RATE = float(os.getenv("DJANGO_CUSTOMLOGGER_SAMPLE_RATE", 1.0))

# Log level: INFO by default (for both dev + prod), override via env
# Allowed values: "DEBUG" or "INFO"
CUSTOMLOGGER_LOG_LEVEL = os.getenv("DJANGO_CUSTOMLOGGER_LOG_LEVEL", "INFO").upper()

# Modules/prefixes to exclude from auto-wrapping
CUSTOMLOGGER_EXCLUDE_MODULES = [
    'django.',
    'django.contrib.',
    'django.db.',
    'django.utils.',
    'django.core.',
    'rest_framework.',
    'auditlog.',
    'debug_toolbar.',
    'corsheaders.',
    'jazzmin.',
    'django_celery_beat.',
    'whitenoise.',
    'django_summernote.',
]

CUSTOMLOGGER_IMPORT_MODULES = [
    "accessioning.ajax.ajax",
    "analysis.views",
    # other modules that are lazily imported
]

# Optional: detect environment
ENV = os.getenv("DJANGO_ENV", "development")  # "development" or "production"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_TZ = True

SERVER_TIME_ZONE = 'UTC'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

JAZZMIN_SETTINGS = {
    'site_title': "GULF COAST PATHOLOGISTS",
    'site_header': 'GULF COAST PATHOLOGISTS',
    'site_brand': ' ',
    'site_logo': 'assets/imgs/logo.png',
    'login_logo': 'assets/imgs/logo.png',
    'copyright': 'GulfCoastPathologists.COM',
    "site_logo_classes": "custom-image",
    "custom_css": "css/app.css",

    'welcome_sign': ' ',
    'order_with_respect_to': ["security", "security.sitetimezone", "security.site", "security.department",
                              "security.jobtype", "security.user",
                              "configuration", "configuration.referencetype",
                              "reporting", "reporting.labelmethod", "reporting.printer",
                              "process", "process.sampletype",
                              "process.containertype", "process.consumabletype",
                              "labresource", "labresource.instrumenttype", "labresource.instrumentmodel",
                              "workflows", "workflows.workflows",
                              "tests", "tests.units", "tests.analyte", "tests.cptcode",
                              "tests.test", "tests.icdcode",
                              "accesioning",
                              "masterdata", "masterdata.client", "masterdata.patient", "masterdata.physician",
                              "masterdata.accessiontype",
                              "wetlabworklist",
                              "analysis", "analysis.reportoption",
                              "analysisworklist", "analysisworklist.accessionreportswrapper",
                              "analysisworklist.accessionhistoricalreportswrapper",
                              "sample", "sample.sample", "ihcworkflow", "ihcworkflow.ihcworkflow",
                              "routinginfo",
                              "auditlog", "audit", "template", "template.accessiontemplate",
                              ],
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"app": "security"}, {"app": "configuration"}, {"app": "reporting"}, {"app": "process"}, {"app": "labresource"},
        {"app": "workflows"},
        {"app": "tests"},
        {"app": "accessioning"}, {"app": "masterdata"},
        {"app": "wetlabworklist"},
        {"app": "sample"},
        {"app": "analysisworklist"}, {"app": "routinginfo"},
        {"app": "auditlog"}, {"app": "audit"}, {"app": "template"}, {"app": "tpcm"}
    ],
    "show_sidebar": True,
    # "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-light",
    "accent": "accent-primary",
    "navbar": "navbar-secondary navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-light-teal",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "sandstone",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True
}

AUTO_LOGOUT = {
    'IDLE_TIME': timedelta(minutes=15),
    'MESSAGE': 'The session has expired. Please login again to continue.',
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'security.User'

# Celery Configuration Options
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/1'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

CELERY_RESULT_BACKEND = 'django-db'

# Celery Beat Configuration
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

CELERY_APP_NAME = 'controllerapp'
CELERY_NAMESPACE = 'CELERY'
CELERY_LOG_FILE_FOR_INFO = 'log/info/task_log/info.log'
CELERY_LOG_FILE_FOR_ERROR = 'log/error/task_log/error.log'
CELERY_LOG_MAX_BYTES = 1024 * 1024 * 300
CELERY_LOG_BACKUP_COUNT = 10

env = environ.Env()
environ.Env.read_env(os.path.join(os.path.dirname(__file__), "..", ".env"))

# AWS Configuration
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="us-east-1")
AWS_S3_KMS_KEY_ARN = env("AWS_KMS_KEY_ARN")
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
BT_PRINT_PORTAL_URI = env("BT_PRINT_PORTAL_URI")

LABEL_HEADER = '/D="%Trigger File Name%" /R=3 /DbTextHeader=3 /C=1 \n%END%'
PRINT_PORTAL_WEB_ROOT = "C:\inetpub\wwwroot\BarTender\wwwroot"

APPLICATION_MODULE_IMAGES_REFERENCE = 'ModuleImages'
IMPORT_EXPORT_SKIP_ADMIN_ACTION_EXPORT_UI = True
APPLICATION_YES_NO_OPTION_REFERENCE = 'YesNoOption'
APPLICATION_DEPARTMENT_NAME_REFERENCE = 'DepartmentName'
APPLICATION_PRINTERCATEGORY_REFERENCE = "printercategory"
APPLICATION_GENDER_TYPE_REFERENCE = "Gender"
APPLICATION_MARITAL_STATUS_REFERENCE = "MaritalStatus"
APPLICATION_SMOKING_STATUS_REFERENCE = "SmokingStatus"
APPLICATION_ACCESSION_CATEGORY_REFERENCE = 'AccessionCategory'
APPLICATION_ACCESSION_TEMPLATE_REFERENCE = 'AccessionTemplate'
APPLICATION_ACCESSION_PREFIX_REFERENCE = 'AccessionPrefix'
APPLICATION_PAYMENT_TYPE_REFERENCE = 'PaymentType'
APPLICATION_ACCESSION_STATUS_REFERENCE = 'AccessionStatus'
APPLICATION_MODALITY_REFERENCE = 'Modality'
APPLICATION_MODEL_REFERENCE = 'Models'
APPLICATION_DOCTOR_CATEGORY = 'DoctorCategory'
APPLICATION_BODY_SITE = 'BodySite'
APPLICATION_COLLECTION_METHOD = 'CollectionMethod'
APPLICATION_GROSS_CODE_REFERENCE = 'GrossCode'
APPLICATION_DESCRIPTIVE_REFERENCE = "Descriptive"
APPLICATION_FILE_FORMAT = "LabelFileFormat"
APPLICATION_DELIMITER = "LabelDelimiter"
APPLICATION_PRINTER_COMMUNICATION_TYPE = "PrinterCommunicationType"
APPLICATION_INPUT_MODE_OPTION_REFERENCE = 'InputMode'
APPLICATION_DATA_TYPE_REFERENCE = 'DataType'
APPLICATION_CATEGORY_REFERENCE = 'Category'
APPLICATION_SUB_SITE_REFERENCE = 'SubSite'
APPLICATION_ATTACHMENT_TYPE = 'AttachmentType'
APPLICATION_MACROS_TYPE_REFERENCE = "Macros Type"
STAINING_TECHNIQUES = 'StainingTechniques'
CONTAINER_TYPE_PARAFFIN_TISSUE_BLOCK = "Paraffin Tissue Block"
CONTAINER_TYPE_SLIDE_UNSTAINED = "Slide - Unstained"
CONTAINER_TYPE_CELL_BLOCK = "Cell Block"
SAMPLE_TYPE_CELL_BUTTON = "Cell Button"
SAMPLE_TYPE_TISSUE = "Tissue"
APPLICATION_PROJECT_EMAIL_REFERENCE = 'ProjectEmailCategory'
TEST_ID_GULF = 'GulfTest'
APPLICATION_ACCESSIONING_DEMOGRAPHIC_FIELDS = 'AccessioningDemographics'

SUMMERNOTE_CONFIG = {
    "iframe": True,
    "summernote": {
        "width": "100%",
        "height": "400px",
        "toolbar": [
            # ["style", ["style"]],
            ["font", ["bold", "underline", "clear"]],
            # ['fontname', ['fontname']],
            ['color', ['color']],
            ["para", ["ul", "ol", "paragraph"]],
            # ['table', ['table']],
            # ["insert", ["picture", "link", "video"]],
            # ['view', ['fullscreen', 'codeview', 'help']],
            ['view', ['fullscreen']],
        ],
    },
}

DEFAULT_REPORT_LOGO_PATH = "static/reports/logo.png"
REPORT_IMAGE_OUTPUT_PATH = "static/output/reports/images"
REPORT_PREVIEW_OUTPUT_PATH = "static/output/reports/preview"
REPORT_FINAL_OUTPUT_PATH = "static/output/reports/final"
REPORT_DIR_INPUT_FOLDER_PATH = "static/reports/"

ATTACHMENT_TYPE_LOGO = "Logo"
ATTACHMENT_TYPE_SIGNATURE = "Signature"

# VitroStainer HL7 Communication
HL7_STAINER_IP = "192.168.1.19"
HL7_STAINER_PORT = 9999
APPLICATION_ROOT_URL = "0.0.0.0"
HL7_LISTENER_PORT = 6660
HL7_TIMEOUT = 30  # seconds
HL7_THREADPOOL_MAX_WORKERS_SENDER = 10
HL7_THREADPOOL_MAX_WORKERS_LISTENER = 50
HL7_THREADPOOL_MAX_WORKERS_PROCESS_MSG = 10
HL7_SERVER_BACKLOG = 100

# --- Email Configuration (Quick Test Only) ---
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "smstudyall@gmail.com"
EMAIL_HOST_PASSWORD = "pqyb iwao zuya ooxq"  # <-- paste your App Password here
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
