# Generated by Django 4.2.7 on 2025-03-03 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0016_alter_department_siteid_alter_jobtype_departmentid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sample', '0002_sample_accession_sample_childsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingInfo',
            fields=[
                ('routing_info_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Routing Info Id')),
                ('from_step', models.CharField(blank=True, max_length=40, null=True, verbose_name='From Step')),
                ('to_step', models.CharField(blank=True, max_length=40, null=True, verbose_name='To Step')),
                ('from_storage', models.CharField(blank=True, max_length=40, null=True, verbose_name='From Storage')),
                ('to_storage', models.CharField(blank=True, max_length=40, null=True, verbose_name='To Storage')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='RoutingCreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='FromDept', to='security.department', verbose_name='From Department')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='FromUser', to=settings.AUTH_USER_MODEL, verbose_name='From User')),
                ('sample_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sample.sample', verbose_name='Sample Id')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ToDept', to='security.department', verbose_name='To Department')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ToUser', to=settings.AUTH_USER_MODEL, verbose_name='To User')),
            ],
            options={
                'verbose_name': 'Routing Info',
                'verbose_name_plural': 'Routing Info',
            },
        ),
    ]
