# Generated by Django 4.2.7 on 2025-09-03 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_alter_reportoption_unique_together_and_more'),
        ('routinginfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinginfo',
            name='report_option_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='analysis.reportoption', verbose_name='Report Option Id'),
        ),
    ]
