# Generated by Django 4.2.7 on 2025-03-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cytoworkflow', '0001_initial'),
        ('ihcworkflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CytoMacro',
            fields=[
                ('cytoworkflow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cytoworkflow.cytoworkflow')),
                ('macro_name', models.CharField(max_length=100, unique=True, verbose_name='Macro Name')),
            ],
            options={
                'verbose_name': 'Cyto Macro',
                'verbose_name_plural': 'Cyto Macros',
            },
            bases=('cytoworkflow.cytoworkflow',),
        ),
        migrations.CreateModel(
            name='IhcMacro',
            fields=[
                ('ihcworkflow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ihcworkflow.ihcworkflow')),
                ('macro_name', models.CharField(max_length=100, unique=True, verbose_name='Macro Name')),
            ],
            options={
                'verbose_name': 'IHC Macro',
                'verbose_name_plural': 'IHC Macros',
            },
            bases=('ihcworkflow.ihcworkflow',),
        ),
    ]
