# Generated by Django 4.2.7 on 2025-08-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accessioning', '0008_accession_is_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessionIHCWrapper',
            fields=[
            ],
            options={
                'verbose_name': 'IHC Worklist',
                'verbose_name_plural': 'IHC Worklist',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accessioning.accession',),
        ),
        migrations.CreateModel(
            name='AccessionSampleWrapper',
            fields=[
            ],
            options={
                'verbose_name': 'Enterprise Worklist',
                'verbose_name_plural': 'Enterprise Worklist',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accessioning.accession',),
        ),
    ]
