# Generated by Django 4.2.7 on 2025-01-30 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=40, verbose_name='Model Id')),
                ('prefix_id', models.CharField(max_length=6, verbose_name='Prefix Id')),
                ('seq_no', models.IntegerField(verbose_name='Sequence No')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Sequence Gen',
                'verbose_name_plural': 'Sequence Gen',
                'unique_together': {('model_id', 'prefix_id')},
            },
        ),
    ]
