# Generated by Django 4.2.7 on 2025-02-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0002_alter_sequencegen_created_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencegen',
            name='prefix_id',
            field=models.CharField(max_length=20, verbose_name='Prefix Id'),
        ),
    ]
