# Generated by Django 4.2.7 on 2025-04-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0004_alter_sequencegen_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencegen',
            name='prefix_id',
            field=models.CharField(max_length=100, verbose_name='Prefix Id'),
        ),
    ]
