# Generated by Django 4.2.7 on 2025-01-20 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('container_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Container Type Id')),
                ('container_type', models.CharField(max_length=40, unique=True, verbose_name='Container Type')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Container Type',
                'verbose_name_plural': 'Container Types',
                'unique_together': {('container_type_id', 'container_type')},
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('sample_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Sample Type Id')),
                ('sample_type', models.CharField(max_length=40, unique=True, verbose_name='Sample Type')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Sample Type',
                'verbose_name_plural': 'Sample Types',
                'unique_together': {('sample_type_id', 'sample_type')},
            },
        ),
        migrations.CreateModel(
            name='ConsumableType',
            fields=[
                ('consumable_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Consumable Type Id')),
                ('consumable_type', models.CharField(max_length=80, unique=True, verbose_name='Consumable Type')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Consumable Type',
                'verbose_name_plural': 'Consumable Types',
            },
        ),
        migrations.CreateModel(
            name='SampleTypeContainerType',
            fields=[
                ('sampletype_containertype_id', models.AutoField(primary_key=True, serialize=False, verbose_name='SampleType_ContainerType_Id')),
                ('container_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.containertype', verbose_name='Container Type Id')),
                ('sample_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.sampletype', verbose_name='Sample Type')),
            ],
            options={
                'verbose_name': 'Sample Type Container Type Map',
                'verbose_name_plural': 'Sample Type',
                'unique_together': {('sample_type_id', 'container_type_id')},
            },
        ),
    ]
