# Generated by Django 4.2.7 on 2025-01-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletypecontainertype',
            name='container_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='process.containertype', verbose_name='Container Type Id'),
        ),
        migrations.AlterField(
            model_name='sampletypecontainertype',
            name='sample_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='process.sampletype', verbose_name='Sample Type'),
        ),
    ]
