# Generated by Django 4.2.7 on 2025-02-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_alter_sampletypecontainertype_container_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertype',
            name='child_sample_creation',
            field=models.BooleanField(default=False, verbose_name='Child Sample Creation'),
        ),
    ]
