# Generated by Django 4.2.7 on 2025-02-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_alter_consumabletype_created_dt_and_more'),
        ('process', '0003_containertype_child_sample_creation'),
    ]

    operations = [
    ]
