# Generated by Django 4.2.7 on 2025-02-06 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process', '0004_merge_20250206_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumabletype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='sampletypecontainertype',
            name='container_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='process.containertype', verbose_name='Container Type Id'),
        ),
        migrations.AlterField(
            model_name='sampletypecontainertype',
            name='sample_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='process.sampletype', verbose_name='Sample Type'),
        ),
    ]
