# Generated by Django 4.2.7 on 2025-03-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_alter_consumabletype_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertype',
            name='gen_block_or_cassette_seq',
            field=models.BooleanField(default=False, verbose_name='Generate Block Or Cassette Sequence'),
        ),
        migrations.AddField(
            model_name='containertype',
            name='gen_slide_seq',
            field=models.BooleanField(default=False, verbose_name='Generate Slide Sequence'),
        ),
    ]
