# Generated by Django 4.2.7 on 2025-05-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_containertype_gen_block_or_cassette_seq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertype',
            name='is_liquid',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, null=True, verbose_name='Is Liquid'),
        ),
    ]
