# Generated by Django 4.2.7 on 2025-12-01 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_workflowstep_backward_movement'),
        ('process', '0007_containertype_is_liquid'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertype',
            name='workflow_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='workflows.workflow', verbose_name='Default Workflow'),
        ),
    ]
