# Generated by Django 4.2.7 on 2025-01-20 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPTCode',
            fields=[
                ('cpt_code_id', models.AutoField(primary_key=True, serialize=False, verbose_name='CPT Code Id')),
                ('cpt_code', models.CharField(max_length=40, unique=True, verbose_name='CPT Code')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'CPT Codes',
                'verbose_name_plural': 'CPT Codes',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Test Id')),
                ('test_name', models.CharField(max_length=40, verbose_name='Test Name')),
                ('version', models.CharField(max_length=3, verbose_name='Version')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('active_flag', models.CharField(blank=True, max_length=10, null=True, verbose_name='Active Flag')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unit Id')),
                ('unit', models.CharField(max_length=40, unique=True, verbose_name='Unit')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
            },
        ),
        migrations.CreateModel(
            name='Macros',
            fields=[
                ('macro_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Macro Id')),
                ('macro', models.CharField(max_length=40, unique=True, verbose_name='Macro')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Macro',
                'verbose_name_plural': 'Macros',
            },
        ),
        migrations.CreateModel(
            name='ICDCode',
            fields=[
                ('icd_code_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ICD Code Id')),
                ('icd_code', models.CharField(max_length=40, unique=True, verbose_name='ICD Code')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'ICD Codes',
                'verbose_name_plural': 'ICD Codes',
            },
        ),
        migrations.CreateModel(
            name='Analyte',
            fields=[
                ('analyte_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Analyte Id')),
                ('analyte', models.CharField(max_length=40, unique=True, verbose_name='Analyte')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.units', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'analyte',
                'verbose_name_plural': 'analytes',
            },
        ),
        migrations.CreateModel(
            name='TestCPTCodeMap',
            fields=[
                ('test_cptcode_map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Test CPTCode Id')),
                ('cpt_code_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.cptcode', verbose_name='CPT Code')),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test CPT Code Map',
                'verbose_name_plural': 'CPT Codes',
                'unique_together': {('test_id', 'cpt_code_id')},
            },
        ),
        migrations.CreateModel(
            name='TestAnalyte',
            fields=[
                ('test_analyte_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Test Analyte Id')),
                ('analyte_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.analyte', verbose_name='Analyte')),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test Analyte',
                'verbose_name_plural': 'Analytes',
                'unique_together': {('test_id', 'analyte_id')},
            },
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(fields=('test_name', 'version'), name='unique_test_name_version'),
        ),
        migrations.AddConstraint(
            model_name='analyte',
            constraint=models.UniqueConstraint(fields=('analyte_id', 'analyte'), name='unique_analyte_id_analyte'),
        ),
    ]
