# Generated by Django 4.2.7 on 2025-01-26 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0004_alter_workflowstep_unique_together_and_more'),
        ('process', '0001_initial'),
        ('labresource', '0001_initial'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='version',
            field=models.IntegerField(verbose_name='Version'),
        ),
        migrations.CreateModel(
            name='TestWorkflowStep',
            fields=[
                ('test_workflow_step_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Test Workflow Step Id')),
                ('sample_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.sampletype', verbose_name='Sample Type')),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test', verbose_name='Test')),
                ('workflow_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflow', verbose_name='Workflow')),
                ('workflow_step_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowstep', verbose_name='Step')),
            ],
            options={
                'verbose_name': 'Test Workflow Step',
                'verbose_name_plural': 'Test Workflow Steps',
                'unique_together': {('test_id', 'workflow_id', 'workflow_step_id', 'sample_type_id')},
            },
        ),
        migrations.CreateModel(
            name='TestWFSTPInstrumentMap',
            fields=[
                ('test_wf_stp_instrument_map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Test Workflow Step Instrument Map Id')),
                ('instrument_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labresource.instrumenttype', verbose_name='Instrument Type')),
                ('sample_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.sampletype', verbose_name='Sample Type')),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test', verbose_name='Test')),
                ('workflow_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflow', verbose_name='Workflow')),
                ('workflow_step_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowstep', verbose_name='Step')),
            ],
            options={
                'verbose_name': 'Test Workflow Step Instrument',
                'verbose_name_plural': 'Test Workflow Step Instruments',
                'unique_together': {('test_id', 'workflow_id', 'workflow_step_id', 'sample_type_id', 'instrument_type_id')},
            },
        ),
        migrations.CreateModel(
            name='TestWFSTPConsumableMap',
            fields=[
                ('test_wf_stp_consumable_map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Test Workflow Step Consumable Map Id')),
                ('consumable_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.consumabletype', verbose_name='Consumable Type')),
                ('sample_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.sampletype', verbose_name='Sample Type')),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test', verbose_name='Test')),
                ('workflow_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflow', verbose_name='Workflow')),
                ('workflow_step_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowstep', verbose_name='Step')),
            ],
            options={
                'verbose_name': 'Test Workflow Step Consumable',
                'verbose_name_plural': 'Test Workflow Step Consumables',
                'unique_together': {('test_id', 'workflow_id', 'workflow_step_id', 'sample_type_id', 'consumable_type_id')},
            },
        ),
        migrations.CreateModel(
            name='TestAttribute',
            fields=[
                ('test_attribute_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Test Attribute Id')),
                ('test_attribute', models.CharField(max_length=80, verbose_name='Test Attribute')),
                ('value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Value')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test Attribute',
                'verbose_name_plural': 'Test Attributes',
                'unique_together': {('test_id', 'test_attribute')},
            },
        ),
    ]
