# Generated by Django 4.2.7 on 2025-01-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_test_version_testworkflowstep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanalyte',
            name='analyte_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.analyte', verbose_name='Analyte'),
        ),
        migrations.AlterField(
            model_name='testanalyte',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='testcptcodemap',
            name='cpt_code_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.cptcode', verbose_name='CPTCode Id'),
        ),
        migrations.AlterField(
            model_name='testcptcodemap',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Test Id'),
        ),
    ]
