# Generated by Django 4.2.7 on 2025-01-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labresource', '0002_alter_instrumentmodel_instrument_type'),
        ('workflows', '0005_alter_workflowstep_workflow_id'),
        ('process', '0002_alter_sampletypecontainertype_container_type_id_and_more'),
        ('tests', '0003_alter_testanalyte_analyte_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyte',
            name='unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.units', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='testattribute',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='testwfstpconsumablemap',
            name='consumable_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='process.consumabletype', verbose_name='Consumable Type'),
        ),
        migrations.AlterField(
            model_name='testwfstpconsumablemap',
            name='sample_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='process.sampletype', verbose_name='Sample Type'),
        ),
        migrations.AlterField(
            model_name='testwfstpconsumablemap',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='testwfstpconsumablemap',
            name='workflow_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow', verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='testwfstpconsumablemap',
            name='workflow_step_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowstep', verbose_name='Step'),
        ),
        migrations.AlterField(
            model_name='testwfstpinstrumentmap',
            name='instrument_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labresource.instrumenttype', verbose_name='Instrument Type'),
        ),
        migrations.AlterField(
            model_name='testwfstpinstrumentmap',
            name='sample_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='process.sampletype', verbose_name='Sample Type'),
        ),
        migrations.AlterField(
            model_name='testwfstpinstrumentmap',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='testwfstpinstrumentmap',
            name='workflow_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow', verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='testwfstpinstrumentmap',
            name='workflow_step_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowstep', verbose_name='Step'),
        ),
        migrations.AlterField(
            model_name='testworkflowstep',
            name='sample_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='process.sampletype', verbose_name='Sample Type'),
        ),
        migrations.AlterField(
            model_name='testworkflowstep',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='testworkflowstep',
            name='workflow_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow', verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='testworkflowstep',
            name='workflow_step_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowstep', verbose_name='Step'),
        ),
    ]
