# Generated by Django 4.2.7 on 2025-01-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_analyte_unit_id_alter_testattribute_test_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macros',
            name='value',
            field=models.TextField(null=True, verbose_name='Value'),
        ),
    ]
