# Generated by Django 4.2.7 on 2025-02-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_macros_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalityModelMap',
            fields=[
                ('modality_model_map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Modality Model Map ID')),
                ('modality', models.CharField(max_length=40, verbose_name='Modality')),
                ('model', models.CharField(max_length=40, verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Modality Model Map',
                'verbose_name_plural': 'Modality Model Maps',
                'unique_together': {('modality', 'model')},
            },
        ),
    ]
