# Generated by Django 4.2.7 on 2025-02-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_analyte_created_dt_alter_cptcode_created_dt_and_more'),
        ('tests', '0006_modalitymodelmap'),
    ]

    operations = [
    ]
