# Generated by Django 4.2.7 on 2025-02-06 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labresource', '0004_alter_instrumentmodel_instrument_type'),
        ('process', '0005_alter_consumabletype_created_by_and_more'),
        ('workflows', '0007_alter_workflow_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0007_merge_20250206_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyte',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='analyte',
            name='unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.units', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='cptcode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='icdcode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='macros',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='testanalyte',
            name='analyte_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.analyte', verbose_name='Analyte'),
        ),
        migrations.AlterField(
            model_name='testanalyte',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='testattribute',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='testattribute',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='testcptcodemap',
            name='cpt_code_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.cptcode', verbose_name='CPTCode Id'),
        ),
        migrations.AlterField(
            model_name='testcptcodemap',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.test', verbose_name='Test Id'),
        ),
        migrations.AlterField(
            model_name='testwfstpconsumablemap',
            name='consumable_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='process.consumabletype', verbose_name='Consumable Type'),
        ),
        migrations.AlterField(
            model_name='testwfstpconsumablemap',
            name='sample_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='process.sampletype', verbose_name='Sample Type'),
        ),
        migrations.AlterField(
            model_name='testwfstpconsumablemap',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='testwfstpconsumablemap',
            name='workflow_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='workflows.workflow', verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='testwfstpconsumablemap',
            name='workflow_step_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='workflows.workflowstep', verbose_name='Step'),
        ),
        migrations.AlterField(
            model_name='testwfstpinstrumentmap',
            name='instrument_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='labresource.instrumenttype', verbose_name='Instrument Type'),
        ),
        migrations.AlterField(
            model_name='testwfstpinstrumentmap',
            name='sample_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='process.sampletype', verbose_name='Sample Type'),
        ),
        migrations.AlterField(
            model_name='testwfstpinstrumentmap',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='testwfstpinstrumentmap',
            name='workflow_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='workflows.workflow', verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='testwfstpinstrumentmap',
            name='workflow_step_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='workflows.workflowstep', verbose_name='Step'),
        ),
        migrations.AlterField(
            model_name='testworkflowstep',
            name='sample_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='process.sampletype', verbose_name='Sample Type'),
        ),
        migrations.AlterField(
            model_name='testworkflowstep',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='testworkflowstep',
            name='workflow_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='workflows.workflow', verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='testworkflowstep',
            name='workflow_step_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='workflows.workflowstep', verbose_name='Step'),
        ),
        migrations.AlterField(
            model_name='units',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
