# Generated by Django 4.2.7 on 2025-02-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_analyte_created_by_alter_analyte_unit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testworkflowstep',
            name='container_type_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Container Type'),
        ),
    ]
