# Generated by Django 4.2.7 on 2025-02-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_alter_consumabletype_created_by_and_more'),
        ('tests', '0009_testworkflowstep_container_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testworkflowstep',
            name='container_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='process.containertype', verbose_name='Container Type'),
        ),
    ]
