# Generated by Django 4.2.7 on 2025-02-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_alter_testworkflowstep_container_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testworkflowstep',
            name='container_type_id',
        ),
    ]
