# Generated by Django 4.2.7 on 2025-02-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_alter_consumabletype_created_by_and_more'),
        ('tests', '0011_remove_testworkflowstep_container_type_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testworkflowstep',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='testworkflowstep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testworkflowstep',
            name='container_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='process.containertype', verbose_name='Container Type'),
        ),
    ]
