# Generated by Django 4.2.7 on 2025-02-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_alter_workflow_created_by_and_more'),
        ('process', '0005_alter_consumabletype_created_by_and_more'),
        ('tests', '0012_alter_testworkflowstep_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testworkflowstep',
            options={'verbose_name': 'Test Workflow Step', 'verbose_name_plural': 'Test Workflow Steps'},
        ),
        migrations.RenameField(
            model_name='testworkflowstep',
            old_name='container_type_id',
            new_name='container_type',
        ),
        migrations.AlterUniqueTogether(
            name='testworkflowstep',
            unique_together={('test_id', 'workflow_id', 'workflow_step_id', 'sample_type_id')},
        ),
    ]
