# Generated by Django 4.2.7 on 2025-02-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_alter_consumabletype_created_by_and_more'),
        ('tests', '0013_alter_testworkflowstep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testwfstpconsumablemap',
            name='container_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='process.containertype', verbose_name='Container Type'),
        ),
        migrations.AddField(
            model_name='testwfstpinstrumentmap',
            name='container_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='process.containertype', verbose_name='Container Type'),
        ),
    ]
