# Generated by Django 4.2.7 on 2025-02-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_alter_workflow_created_by_and_more'),
        ('process', '0005_alter_consumabletype_created_by_and_more'),
        ('tests', '0014_testwfstpconsumablemap_container_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testworkflowstep',
            unique_together={('test_id', 'workflow_id', 'workflow_step_id', 'sample_type_id', 'container_type')},
        ),
    ]
