# Generated by Django 4.2.7 on 2025-03-03 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0015_alter_testworkflowstep_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testattribute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testattribute',
            name='test_workflow_step_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.testworkflowstep', verbose_name='Test Workflow Step'),
        ),
        migrations.AddField(
            model_name='testworkflowstep',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='testworkflowstep',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterUniqueTogether(
            name='testattribute',
            unique_together={('test_id', 'test_workflow_step_id', 'test_attribute')},
        ),
        migrations.CreateModel(
            name='WorkflowStepConfigField',
            fields=[
                ('ws_config_field_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Workflow Step Config Field Id')),
                ('model', models.CharField(blank=True, max_length=80, null=True, verbose_name='Model')),
                ('field_id', models.CharField(max_length=40, verbose_name='Model Column ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('test_workflow_step_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.testworkflowstep', verbose_name='Test Workflow Step')),
            ],
            options={
                'verbose_name': 'Workflow Step Config Field',
                'verbose_name_plural': 'Workflow Step Config Fields',
                'unique_together': {('test_workflow_step_id', 'model', 'field_id')},
            },
        ),
    ]
