# Generated by Django 4.2.7 on 2025-03-31 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0016_alter_testattribute_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestWorkflowStepActionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=200, null=True, verbose_name='Action')),
                ('action_method', models.CharField(blank=True, max_length=200, null=True, verbose_name='Action Method')),
                ('sequence', models.IntegerField(verbose_name='Sequence No')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('testwflwstepmap_id', models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.testworkflowstep', verbose_name='Model Id')),
            ],
            options={
                'verbose_name': 'Test Workflow Action',
                'verbose_name_plural': 'Test Workflow Actions',
                'unique_together': {('testwflwstepmap_id', 'action', 'action_method')},
            },
        ),
    ]
