# Generated by Django 4.2.7 on 2025-04-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_testworkflowstepactionmap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModalityModelMap',
        ),
    ]
