# Generated by Django 4.2.7 on 2025-05-03 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_referencetype_created_by_and_more'),
        ('tests', '0018_delete_modalitymodelmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanalyte',
            name='condition',
            field=models.CharField(blank=True, choices=[('and', 'AND'), ('or', 'OR')], max_length=40, null=True, verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='testanalyte',
            name='data_type',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Data Type'),
        ),
        migrations.AddField(
            model_name='testanalyte',
            name='decimal_precision',
            field=models.IntegerField(blank=True, null=True, verbose_name='Decimal Precision'),
        ),
        migrations.AddField(
            model_name='testanalyte',
            name='dropdown_reference_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.referencetype', verbose_name='Dropdown Reftype'),
        ),
        migrations.AddField(
            model_name='testanalyte',
            name='dropdown_sql',
            field=models.TextField(blank=True, null=True, verbose_name='Dropdown Sql'),
        ),
        migrations.AddField(
            model_name='testanalyte',
            name='input_mode',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Input Mode'),
        ),
        migrations.AddField(
            model_name='testanalyte',
            name='operator1',
            field=models.CharField(blank=True, choices=[('==', '='), ('<', '<'), ('<=', '<='), ('>', '>'), ('>=', '>=')], max_length=40, null=True, verbose_name='Operator-1'),
        ),
        migrations.AddField(
            model_name='testanalyte',
            name='operator2',
            field=models.CharField(blank=True, choices=[('==', '='), ('<', '<'), ('<=', '<='), ('>', '>'), ('>=', '>=')], max_length=40, null=True, verbose_name='Operator-2'),
        ),
        migrations.AddField(
            model_name='testanalyte',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.units', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='testanalyte',
            name='value1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Value-1'),
        ),
        migrations.AddField(
            model_name='testanalyte',
            name='value2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Value-2'),
        ),
        migrations.AddField(
            model_name='testanalyte',
            name='value_text',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Text Value (For String Comparison)'),
        ),
    ]
