# Generated by Django 4.2.7 on 2025-05-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_testanalyte_condition_testanalyte_data_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='smear_process',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Smear Process'),
        ),
    ]
