# Generated by Django 4.2.7 on 2025-05-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_test_smear_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanalyte',
            name='is_reportable',
            field=models.BooleanField(default=True, verbose_name='Is Reportable?'),
        ),
        migrations.AddField(
            model_name='testworkflowstep',
            name='backward_movement',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, null=True, verbose_name='Backward Movement'),
        ),
        migrations.AlterField(
            model_name='testanalyte',
            name='value_text',
            field=models.TextField(blank=True, help_text="Enter the string value to use for comparison. For multiple allowed values, separate each with a semicolon (;). Example: 'Positive;Negative;Inconclusive'.", max_length=80, null=True, verbose_name='Text Value'),
        ),
    ]
