# Generated by Django 4.2.7 on 2025-08-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_testanalyte_is_reportable_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Macros',
        ),
    ]
