# Generated by Django 4.2.7 on 2025-09-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_alter_workflow_accession_type'),
        ('tests', '0022_delete_macros'),
    ]

    operations = [
        migrations.AddField(
            model_name='testworkflowstepactionmap',
            name='workflow_step_id',
            field=models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowstep', verbose_name='Workflow Step Id'),
        ),
        migrations.AddField(
            model_name='workflowstepconfigfield',
            name='workflow_step_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='workflows.workflowstep', verbose_name='Workflow Step Id'),
        ),
    ]
