# Generated by Django 4.2.7 on 2025-01-11 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceType',
            fields=[
                ('reference_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Reference_Type_Id')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Reference Type',
                'verbose_name_plural': 'Reference Type',
            },
        ),
        migrations.CreateModel(
            name='RefValues',
            fields=[
                ('ref_value_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Ref_Value_id')),
                ('value', models.CharField(max_length=80, verbose_name='Value')),
                ('display_value', models.CharField(max_length=200, verbose_name='Display Value')),
                ('reftype_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.referencetype', verbose_name='Reference Type')),
            ],
            options={
                'verbose_name': 'RefValues',
                'verbose_name_plural': 'RefValues',
                'unique_together': {('reftype_id', 'value')},
            },
        ),
    ]
