# Generated by Django 4.2.7 on 2025-02-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencetype',
            name='is_system_level',
            field=models.BooleanField(default=False, verbose_name='System Level'),
        ),
    ]
