# Generated by Django 4.2.7 on 2025-02-05 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0002_referencetype_is_system_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencetype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='referencetype',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='refvalues',
            name='reftype_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configuration.referencetype', verbose_name='Reference Type'),
        ),
    ]
